// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GenerateStoryStreamData, GenerateStoryStreamResponses, GetAppInfoData, GetAppInfoResponses, GetAuthMeData, GetAuthMeResponses, GetBoardsData, GetBoardsResponses, GetStoriesData, GetStoriesResponses, GetStoryData, GetStoryErrors, GetStoryMetricsData, GetStoryMetricsResponses, GetStoryResponses, GetStoryStreamData, GetStoryStreamResponses, PostAuthLoginData, PostAuthLoginResponses, PostAuthLogoutData, PostAuthLogoutResponses, UpdateBoardData, UpdateBoardErrors, UpdateBoardResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getAppInfo = <ThrowOnError extends boolean = false>(options?: Options<GetAppInfoData, ThrowOnError>) => (options?.client ?? client).get<GetAppInfoResponses, unknown, ThrowOnError>({ url: '/', ...options });

export const getBoards = <ThrowOnError extends boolean = false>(options?: Options<GetBoardsData, ThrowOnError>) => (options?.client ?? client).get<GetBoardsResponses, unknown, ThrowOnError>({ url: '/boards', ...options });

export const updateBoard = <ThrowOnError extends boolean = false>(options: Options<UpdateBoardData, ThrowOnError>) => (options.client ?? client).post<UpdateBoardResponses, UpdateBoardErrors, ThrowOnError>({
    url: '/boards/{boardId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getStories = <ThrowOnError extends boolean = false>(options?: Options<GetStoriesData, ThrowOnError>) => (options?.client ?? client).get<GetStoriesResponses, unknown, ThrowOnError>({ url: '/stories', ...options });

export const getStoryMetrics = <ThrowOnError extends boolean = false>(options?: Options<GetStoryMetricsData, ThrowOnError>) => (options?.client ?? client).get<GetStoryMetricsResponses, unknown, ThrowOnError>({ url: '/stories/metrics', ...options });

export const getStory = <ThrowOnError extends boolean = false>(options: Options<GetStoryData, ThrowOnError>) => (options.client ?? client).get<GetStoryResponses, GetStoryErrors, ThrowOnError>({ url: '/stories/{storyId}', ...options });

export const getStoryStream = <ThrowOnError extends boolean = false>(options: Options<GetStoryStreamData, ThrowOnError>) => (options.client ?? client).get<GetStoryStreamResponses, unknown, ThrowOnError>({ url: '/stories/{storyId}/_stream', ...options });

export const generateStoryStream = <ThrowOnError extends boolean = false>(options: Options<GenerateStoryStreamData, ThrowOnError>) => (options.client ?? client).post<GenerateStoryStreamResponses, unknown, ThrowOnError>({
    url: '/stories/_stream',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>) => (options.client ?? client).post<PostAuthLoginResponses, unknown, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAuthMe = <ThrowOnError extends boolean = false>(options?: Options<GetAuthMeData, ThrowOnError>) => (options?.client ?? client).get<GetAuthMeResponses, unknown, ThrowOnError>({ url: '/auth/me', ...options });

export const postAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>) => (options?.client ?? client).post<PostAuthLogoutResponses, unknown, ThrowOnError>({ url: '/auth/logout', ...options });
