// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5000/' | (string & {});
};

export type AgentPersonality = 'Casual' | 'Balanced' | 'Business';

export type AppInfo = {
    appName: string;
    appVersion: string;
};

export type ConversationListItem = {
    conversationId: string;
    participantExternalId: string;
    channel: MessageChannel;
    lastMessagePreview: null | string;
    lastMessageAt: null | string;
    lastMessageRole: null | MessageRole;
    unreadCount: number;
    hasUnread: boolean;
};

export type ConversationMessageItem = {
    messageId: string;
    role: MessageRole;
    content: string;
    from: string;
    to: string;
    occurredAt: string;
    isRead: boolean;
    readAt: null | string;
};

export type CreateSubscriptionOnboardingAgentResult = {
    agentId: string;
    state: GetSubscriptionOnboardingStateResult;
};

export type CurrentUserResult = {
    id: string;
    email: string;
    displayName: string;
    roles: Array<string>;
    activeSubscriptionId: null | string;
    isOnboarded: boolean;
};

export type DeleteSubscriptionSquareConnectionResult = {
    disconnected: boolean;
};

export type ExternalLoginProviderItem = {
    name: string;
    displayName: string;
};

export type GetActiveSubscriptionResult = {
    subscriptionId: string;
};

export type GetAgentConversationsResult = {
    items?: Array<ConversationListItem>;
    hasNextPage?: boolean;
    skip?: number;
    take?: number;
};

export type GetConversationMessagesResult = {
    items?: Array<ConversationMessageItem>;
    hasNextPage?: boolean;
    skip?: number;
    take?: number;
};

export type GetExternalLoginProvidersResult = {
    providers: Array<ExternalLoginProviderItem>;
};

export type GetSubscriptionOnboardingStateResult = {
    status: string;
    currentStep: string;
    steps: Array<OnboardingStepState>;
    primaryAgentId: null | string;
    canFinalize: boolean;
};

export type GetSubscriptionSquareConnectionProbeResult = {
    isConnected: boolean;
    merchantId: string;
    accessTokenExpiresAtUtc: string;
    scopes: Array<string>;
};

export type IngestTelegramMessageInput = {
    message?: null | TelegramMessageInput;
};

export type IngestTwilioTextInput = {
    toCountry?: null | string;
    toState?: null | string;
    smsMessageSid?: null | string;
    numMedia?: null | string;
    toCity?: null | string;
    fromZip?: null | string;
    smsSid?: null | string;
    fromState?: null | string;
    smsStatus?: null | string;
    fromCity?: null | string;
    body?: string;
    fromCountry?: null | string;
    to?: string;
    toZip?: null | string;
    numSegments?: null | string;
    messageSid?: null | string;
    accountSid?: null | string;
    from?: string;
    apiVersion?: null | string;
};

export type MarkConversationMessageReadResult = {
    messageId: string;
    isRead: boolean;
    readAt: null | string;
    conversationUnreadCount: number;
};

export type MarkConversationReadResult = {
    conversationId: string;
    markedCount: number;
    conversationUnreadCount: number;
};

export type MessageChannel = 'WhatsApp' | 'Telegram' | 'SMS';

export type MessageRole = 'Customer' | 'Agent' | 'Operator';

export type OnboardingErrorResult = {
    errorCode: string;
    message: string;
};

export type OnboardingStepState = {
    step: string;
    status: string;
    isSkippable: boolean;
    dependsOn: Array<string>;
};

export type PatchOnboardingAgentChannelsInput = {
    twilioPhoneNumber: null | string;
    telegramBotToken: null | string;
    whatsappNumber: null | string;
};

export type PatchOnboardingAgentProfileInput = {
    name: null | string;
    personality: null | AgentPersonality;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: number;
    detail?: null | string;
    instance?: null | string;
};

export type SquareConnectionErrorResult = {
    errorCode: string;
    message: string;
};

export type StartSubscriptionSquareConnectAuthorizeResult = {
    authorizeUrl: string;
};

export type TelegramChatInput = {
    id?: number;
};

export type TelegramMessageInput = {
    text?: null | string;
    date?: number;
    from?: null | TelegramUserInput;
    chat?: null | TelegramChatInput;
};

export type TelegramUserInput = {
    id?: number;
};

export type GetAppInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetAppInfoResponses = {
    /**
     * OK
     */
    200: AppInfo;
};

export type GetAppInfoResponse = GetAppInfoResponses[keyof GetAppInfoResponses];

export type PostWebhooksTelegramByBotTokenData = {
    body: IngestTelegramMessageInput;
    path: {
        botToken: string;
    };
    query?: never;
    url: '/webhooks/telegram/{botToken}';
};

export type PostWebhooksTelegramByBotTokenErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostWebhooksTelegramByBotTokenError = PostWebhooksTelegramByBotTokenErrors[keyof PostWebhooksTelegramByBotTokenErrors];

export type PostWebhooksTelegramByBotTokenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetOnboardingSquareConnectCallbackData = {
    body?: never;
    path?: never;
    query?: {
        code?: string;
        state?: string;
        error?: string;
    };
    url: '/onboarding/square/connect/callback';
};

export type GetOnboardingSquareConnectCallbackResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type IngestTextData = {
    body: IngestTwilioTextInput;
    path?: never;
    query?: never;
    url: '/webhooks/twilio/text';
};

export type IngestTextErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type IngestTextError = IngestTextErrors[keyof IngestTextErrors];

export type IngestTextResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAuthProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/providers';
};

export type GetAuthProvidersErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetAuthProvidersError = GetAuthProvidersErrors[keyof GetAuthProvidersErrors];

export type GetAuthProvidersResponses = {
    /**
     * OK
     */
    200: GetExternalLoginProvidersResult;
};

export type GetAuthProvidersResponse = GetAuthProvidersResponses[keyof GetAuthProvidersResponses];

export type GetAuthProvidersByProviderAuthorizeData = {
    body?: never;
    path: {
        provider: string;
    };
    query?: {
        returnUrl?: string;
    };
    url: '/auth/providers/{provider}/authorize';
};

export type GetAuthProvidersByProviderAuthorizeErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetAuthProvidersByProviderAuthorizeError = GetAuthProvidersByProviderAuthorizeErrors[keyof GetAuthProvidersByProviderAuthorizeErrors];

export type GetAuthExternalCallbackData = {
    body?: never;
    path?: never;
    query?: {
        returnUrl?: string;
        remoteError?: string;
    };
    url: '/auth/external-callback';
};

export type GetAuthExternalCallbackErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetAuthExternalCallbackError = GetAuthExternalCallbackErrors[keyof GetAuthExternalCallbackErrors];

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetAuthMeErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetAuthMeError = GetAuthMeErrors[keyof GetAuthMeErrors];

export type GetAuthMeResponses = {
    /**
     * OK
     */
    200: CurrentUserResult;
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAgentsByAgentIdConversationsData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/agents/{agentId}/conversations';
};

export type GetAgentsByAgentIdConversationsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetAgentsByAgentIdConversationsError = GetAgentsByAgentIdConversationsErrors[keyof GetAgentsByAgentIdConversationsErrors];

export type GetAgentsByAgentIdConversationsResponses = {
    /**
     * OK
     */
    200: GetAgentConversationsResult;
};

export type GetAgentsByAgentIdConversationsResponse = GetAgentsByAgentIdConversationsResponses[keyof GetAgentsByAgentIdConversationsResponses];

export type GetAgentsByAgentIdConversationsByConversationIdMessagesData = {
    body?: never;
    path: {
        agentId: string;
        conversationId: string;
    };
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/agents/{agentId}/conversations/{conversationId}/messages';
};

export type GetAgentsByAgentIdConversationsByConversationIdMessagesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetAgentsByAgentIdConversationsByConversationIdMessagesError = GetAgentsByAgentIdConversationsByConversationIdMessagesErrors[keyof GetAgentsByAgentIdConversationsByConversationIdMessagesErrors];

export type GetAgentsByAgentIdConversationsByConversationIdMessagesResponses = {
    /**
     * OK
     */
    200: GetConversationMessagesResult;
};

export type GetAgentsByAgentIdConversationsByConversationIdMessagesResponse = GetAgentsByAgentIdConversationsByConversationIdMessagesResponses[keyof GetAgentsByAgentIdConversationsByConversationIdMessagesResponses];

export type PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadData = {
    body?: never;
    path: {
        agentId: string;
        conversationId: string;
        messageId: string;
    };
    query?: never;
    url: '/agents/{agentId}/conversations/{conversationId}/messages/{messageId}/read';
};

export type PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadError = PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadErrors[keyof PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadErrors];

export type PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadResponses = {
    /**
     * OK
     */
    200: MarkConversationMessageReadResult;
};

export type PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadResponse = PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadResponses[keyof PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadResponses];

export type PatchAgentsByAgentIdConversationsByConversationIdReadData = {
    body?: never;
    path: {
        agentId: string;
        conversationId: string;
    };
    query?: never;
    url: '/agents/{agentId}/conversations/{conversationId}/read';
};

export type PatchAgentsByAgentIdConversationsByConversationIdReadErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PatchAgentsByAgentIdConversationsByConversationIdReadError = PatchAgentsByAgentIdConversationsByConversationIdReadErrors[keyof PatchAgentsByAgentIdConversationsByConversationIdReadErrors];

export type PatchAgentsByAgentIdConversationsByConversationIdReadResponses = {
    /**
     * OK
     */
    200: MarkConversationReadResult;
};

export type PatchAgentsByAgentIdConversationsByConversationIdReadResponse = PatchAgentsByAgentIdConversationsByConversationIdReadResponses[keyof PatchAgentsByAgentIdConversationsByConversationIdReadResponses];

export type PostOnboardingSubscriptionsBySubscriptionIdSquareConnectAuthorizeData = {
    body?: never;
    path: {
        subscriptionId: string;
    };
    query?: {
        returnUrl?: string;
    };
    url: '/onboarding/subscriptions/{subscriptionId}/square/connect/authorize';
};

export type PostOnboardingSubscriptionsBySubscriptionIdSquareConnectAuthorizeErrors = {
    /**
     * Bad Request
     */
    400: SquareConnectionErrorResult;
    /**
     * Unauthorized
     */
    401: SquareConnectionErrorResult;
    /**
     * Forbidden
     */
    403: SquareConnectionErrorResult;
};

export type PostOnboardingSubscriptionsBySubscriptionIdSquareConnectAuthorizeError = PostOnboardingSubscriptionsBySubscriptionIdSquareConnectAuthorizeErrors[keyof PostOnboardingSubscriptionsBySubscriptionIdSquareConnectAuthorizeErrors];

export type PostOnboardingSubscriptionsBySubscriptionIdSquareConnectAuthorizeResponses = {
    /**
     * OK
     */
    200: StartSubscriptionSquareConnectAuthorizeResult;
};

export type PostOnboardingSubscriptionsBySubscriptionIdSquareConnectAuthorizeResponse = PostOnboardingSubscriptionsBySubscriptionIdSquareConnectAuthorizeResponses[keyof PostOnboardingSubscriptionsBySubscriptionIdSquareConnectAuthorizeResponses];

export type PostSubscriptionsBySubscriptionIdSquareConnectAuthorizeData = {
    body?: never;
    path: {
        subscriptionId: string;
    };
    query?: {
        returnUrl?: string;
    };
    url: '/subscriptions/{subscriptionId}/square/connect/authorize';
};

export type PostSubscriptionsBySubscriptionIdSquareConnectAuthorizeErrors = {
    /**
     * Bad Request
     */
    400: SquareConnectionErrorResult;
    /**
     * Unauthorized
     */
    401: SquareConnectionErrorResult;
    /**
     * Forbidden
     */
    403: SquareConnectionErrorResult;
};

export type PostSubscriptionsBySubscriptionIdSquareConnectAuthorizeError = PostSubscriptionsBySubscriptionIdSquareConnectAuthorizeErrors[keyof PostSubscriptionsBySubscriptionIdSquareConnectAuthorizeErrors];

export type PostSubscriptionsBySubscriptionIdSquareConnectAuthorizeResponses = {
    /**
     * OK
     */
    200: StartSubscriptionSquareConnectAuthorizeResult;
};

export type PostSubscriptionsBySubscriptionIdSquareConnectAuthorizeResponse = PostSubscriptionsBySubscriptionIdSquareConnectAuthorizeResponses[keyof PostSubscriptionsBySubscriptionIdSquareConnectAuthorizeResponses];

export type DeleteSubscriptionsBySubscriptionIdSquareConnectionData = {
    body?: never;
    path: {
        subscriptionId: string;
    };
    query?: never;
    url: '/subscriptions/{subscriptionId}/square/connection';
};

export type DeleteSubscriptionsBySubscriptionIdSquareConnectionErrors = {
    /**
     * Bad Request
     */
    400: SquareConnectionErrorResult;
    /**
     * Unauthorized
     */
    401: SquareConnectionErrorResult;
    /**
     * Forbidden
     */
    403: SquareConnectionErrorResult;
    /**
     * Not Found
     */
    404: SquareConnectionErrorResult;
};

export type DeleteSubscriptionsBySubscriptionIdSquareConnectionError = DeleteSubscriptionsBySubscriptionIdSquareConnectionErrors[keyof DeleteSubscriptionsBySubscriptionIdSquareConnectionErrors];

export type DeleteSubscriptionsBySubscriptionIdSquareConnectionResponses = {
    /**
     * OK
     */
    200: DeleteSubscriptionSquareConnectionResult;
};

export type DeleteSubscriptionsBySubscriptionIdSquareConnectionResponse = DeleteSubscriptionsBySubscriptionIdSquareConnectionResponses[keyof DeleteSubscriptionsBySubscriptionIdSquareConnectionResponses];

export type GetSubscriptionsBySubscriptionIdSquareConnectionProbeData = {
    body?: never;
    path: {
        subscriptionId: string;
    };
    query?: never;
    url: '/subscriptions/{subscriptionId}/square/connection/probe';
};

export type GetSubscriptionsBySubscriptionIdSquareConnectionProbeErrors = {
    /**
     * Bad Request
     */
    400: SquareConnectionErrorResult;
    /**
     * Unauthorized
     */
    401: SquareConnectionErrorResult;
    /**
     * Forbidden
     */
    403: SquareConnectionErrorResult;
    /**
     * Not Found
     */
    404: SquareConnectionErrorResult;
};

export type GetSubscriptionsBySubscriptionIdSquareConnectionProbeError = GetSubscriptionsBySubscriptionIdSquareConnectionProbeErrors[keyof GetSubscriptionsBySubscriptionIdSquareConnectionProbeErrors];

export type GetSubscriptionsBySubscriptionIdSquareConnectionProbeResponses = {
    /**
     * OK
     */
    200: GetSubscriptionSquareConnectionProbeResult;
};

export type GetSubscriptionsBySubscriptionIdSquareConnectionProbeResponse = GetSubscriptionsBySubscriptionIdSquareConnectionProbeResponses[keyof GetSubscriptionsBySubscriptionIdSquareConnectionProbeResponses];

export type GetOnboardingSubscriptionsActiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/onboarding/subscriptions/active';
};

export type GetOnboardingSubscriptionsActiveErrors = {
    /**
     * Unauthorized
     */
    401: OnboardingErrorResult;
    /**
     * Not Found
     */
    404: OnboardingErrorResult;
};

export type GetOnboardingSubscriptionsActiveError = GetOnboardingSubscriptionsActiveErrors[keyof GetOnboardingSubscriptionsActiveErrors];

export type GetOnboardingSubscriptionsActiveResponses = {
    /**
     * OK
     */
    200: GetActiveSubscriptionResult;
};

export type GetOnboardingSubscriptionsActiveResponse = GetOnboardingSubscriptionsActiveResponses[keyof GetOnboardingSubscriptionsActiveResponses];

export type GetOnboardingSubscriptionsBySubscriptionIdStateData = {
    body?: never;
    path: {
        subscriptionId: string;
    };
    query?: never;
    url: '/onboarding/subscriptions/{subscriptionId}/state';
};

export type GetOnboardingSubscriptionsBySubscriptionIdStateErrors = {
    /**
     * Unauthorized
     */
    401: OnboardingErrorResult;
    /**
     * Forbidden
     */
    403: OnboardingErrorResult;
    /**
     * Not Found
     */
    404: OnboardingErrorResult;
};

export type GetOnboardingSubscriptionsBySubscriptionIdStateError = GetOnboardingSubscriptionsBySubscriptionIdStateErrors[keyof GetOnboardingSubscriptionsBySubscriptionIdStateErrors];

export type GetOnboardingSubscriptionsBySubscriptionIdStateResponses = {
    /**
     * OK
     */
    200: GetSubscriptionOnboardingStateResult;
};

export type GetOnboardingSubscriptionsBySubscriptionIdStateResponse = GetOnboardingSubscriptionsBySubscriptionIdStateResponses[keyof GetOnboardingSubscriptionsBySubscriptionIdStateResponses];

export type PostOnboardingSubscriptionsBySubscriptionIdAgentsData = {
    body?: never;
    path: {
        subscriptionId: string;
    };
    query?: never;
    url: '/onboarding/subscriptions/{subscriptionId}/agents';
};

export type PostOnboardingSubscriptionsBySubscriptionIdAgentsErrors = {
    /**
     * Unauthorized
     */
    401: OnboardingErrorResult;
    /**
     * Forbidden
     */
    403: OnboardingErrorResult;
    /**
     * Not Found
     */
    404: OnboardingErrorResult;
};

export type PostOnboardingSubscriptionsBySubscriptionIdAgentsError = PostOnboardingSubscriptionsBySubscriptionIdAgentsErrors[keyof PostOnboardingSubscriptionsBySubscriptionIdAgentsErrors];

export type PostOnboardingSubscriptionsBySubscriptionIdAgentsResponses = {
    /**
     * OK
     */
    200: CreateSubscriptionOnboardingAgentResult;
};

export type PostOnboardingSubscriptionsBySubscriptionIdAgentsResponse = PostOnboardingSubscriptionsBySubscriptionIdAgentsResponses[keyof PostOnboardingSubscriptionsBySubscriptionIdAgentsResponses];

export type PatchOnboardingAgentsByAgentIdProfileData = {
    body: PatchOnboardingAgentProfileInput;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/onboarding/agents/{agentId}/profile';
};

export type PatchOnboardingAgentsByAgentIdProfileErrors = {
    /**
     * Bad Request
     */
    400: OnboardingErrorResult;
    /**
     * Unauthorized
     */
    401: OnboardingErrorResult;
    /**
     * Forbidden
     */
    403: OnboardingErrorResult;
    /**
     * Not Found
     */
    404: OnboardingErrorResult;
};

export type PatchOnboardingAgentsByAgentIdProfileError = PatchOnboardingAgentsByAgentIdProfileErrors[keyof PatchOnboardingAgentsByAgentIdProfileErrors];

export type PatchOnboardingAgentsByAgentIdProfileResponses = {
    /**
     * OK
     */
    200: GetSubscriptionOnboardingStateResult;
};

export type PatchOnboardingAgentsByAgentIdProfileResponse = PatchOnboardingAgentsByAgentIdProfileResponses[keyof PatchOnboardingAgentsByAgentIdProfileResponses];

export type PatchOnboardingAgentsByAgentIdChannelsData = {
    body: PatchOnboardingAgentChannelsInput;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/onboarding/agents/{agentId}/channels';
};

export type PatchOnboardingAgentsByAgentIdChannelsErrors = {
    /**
     * Bad Request
     */
    400: OnboardingErrorResult;
    /**
     * Unauthorized
     */
    401: OnboardingErrorResult;
    /**
     * Forbidden
     */
    403: OnboardingErrorResult;
    /**
     * Not Found
     */
    404: OnboardingErrorResult;
};

export type PatchOnboardingAgentsByAgentIdChannelsError = PatchOnboardingAgentsByAgentIdChannelsErrors[keyof PatchOnboardingAgentsByAgentIdChannelsErrors];

export type PatchOnboardingAgentsByAgentIdChannelsResponses = {
    /**
     * OK
     */
    200: GetSubscriptionOnboardingStateResult;
};

export type PatchOnboardingAgentsByAgentIdChannelsResponse = PatchOnboardingAgentsByAgentIdChannelsResponses[keyof PatchOnboardingAgentsByAgentIdChannelsResponses];

export type PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsData = {
    body?: never;
    path: {
        subscriptionId: string;
    };
    query?: never;
    url: '/onboarding/subscriptions/{subscriptionId}/members/invitations';
};

export type PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsErrors = {
    /**
     * Bad Request
     */
    400: OnboardingErrorResult;
    /**
     * Unauthorized
     */
    401: OnboardingErrorResult;
    /**
     * Forbidden
     */
    403: OnboardingErrorResult;
    /**
     * Not Found
     */
    404: OnboardingErrorResult;
};

export type PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsError = PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsErrors[keyof PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsErrors];

export type PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsResponses = {
    /**
     * OK
     */
    200: GetSubscriptionOnboardingStateResult;
};

export type PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsResponse = PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsResponses[keyof PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsResponses];

export type PostOnboardingSubscriptionsBySubscriptionIdFinalizeData = {
    body?: never;
    path: {
        subscriptionId: string;
    };
    query?: never;
    url: '/onboarding/subscriptions/{subscriptionId}/finalize';
};

export type PostOnboardingSubscriptionsBySubscriptionIdFinalizeErrors = {
    /**
     * Bad Request
     */
    400: OnboardingErrorResult;
    /**
     * Unauthorized
     */
    401: OnboardingErrorResult;
    /**
     * Forbidden
     */
    403: OnboardingErrorResult;
    /**
     * Not Found
     */
    404: OnboardingErrorResult;
};

export type PostOnboardingSubscriptionsBySubscriptionIdFinalizeError = PostOnboardingSubscriptionsBySubscriptionIdFinalizeErrors[keyof PostOnboardingSubscriptionsBySubscriptionIdFinalizeErrors];

export type PostOnboardingSubscriptionsBySubscriptionIdFinalizeResponses = {
    /**
     * OK
     */
    200: GetSubscriptionOnboardingStateResult;
};

export type PostOnboardingSubscriptionsBySubscriptionIdFinalizeResponse = PostOnboardingSubscriptionsBySubscriptionIdFinalizeResponses[keyof PostOnboardingSubscriptionsBySubscriptionIdFinalizeResponses];
