// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5000/' | (string & {});
};

export type AppInfo = {
    appName: string;
    appVersion: string;
};

export type ConversationListItem = {
    conversationId: string;
    participantExternalId: string;
    channel: MessageChannel;
    lastMessagePreview: null | string;
    lastMessageAt: null | string;
    lastMessageRole: null | MessageRole;
    unreadCount: number;
    hasUnread: boolean;
};

export type ConversationMessageItem = {
    messageId: string;
    role: MessageRole;
    content: string;
    from: string;
    to: string;
    occurredAt: string;
    isRead: boolean;
    readAt: null | string;
};

export type CurrentUserResult = {
    id: string;
    email: string;
    displayName: string;
    roles: Array<string>;
};

export type ExternalLoginProviderItem = {
    name: string;
    displayName: string;
};

export type GetAgentConversationsResult = {
    items?: Array<ConversationListItem>;
    hasNextPage?: boolean;
    skip?: number;
    take?: number;
};

export type GetConversationMessagesResult = {
    items?: Array<ConversationMessageItem>;
    hasNextPage?: boolean;
    skip?: number;
    take?: number;
};

export type GetExternalLoginProvidersResult = {
    providers: Array<ExternalLoginProviderItem>;
};

export type IngestTelegramMessageInput = {
    message?: null | TelegramMessageInput;
};

export type IngestTwilioTextInput = {
    toCountry?: null | string;
    toState?: null | string;
    smsMessageSid?: null | string;
    numMedia?: null | string;
    toCity?: null | string;
    fromZip?: null | string;
    smsSid?: null | string;
    fromState?: null | string;
    smsStatus?: null | string;
    fromCity?: null | string;
    body?: string;
    fromCountry?: null | string;
    to?: string;
    toZip?: null | string;
    numSegments?: null | string;
    messageSid?: null | string;
    accountSid?: null | string;
    from?: string;
    apiVersion?: null | string;
};

export type MarkConversationMessageReadResult = {
    messageId: string;
    isRead: boolean;
    readAt: null | string;
    conversationUnreadCount: number;
};

export type MarkConversationReadResult = {
    conversationId: string;
    markedCount: number;
    conversationUnreadCount: number;
};

export type MessageChannel = 'WhatsApp' | 'Telegram' | 'SMS';

export type MessageRole = 'Customer' | 'Agent' | 'Operator';

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: number;
    detail?: null | string;
    instance?: null | string;
};

export type TelegramMessageInput = {
    text?: null | string;
    date?: number;
    from?: null | TelegramUserInput;
};

export type TelegramUserInput = {
    id?: number;
};

export type GetAppInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetAppInfoResponses = {
    /**
     * OK
     */
    200: AppInfo;
};

export type GetAppInfoResponse = GetAppInfoResponses[keyof GetAppInfoResponses];

export type PostWebhooksTelegramByBotTokenData = {
    body: IngestTelegramMessageInput;
    path: {
        botToken: string;
    };
    query?: never;
    url: '/webhooks/telegram/{botToken}';
};

export type PostWebhooksTelegramByBotTokenErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostWebhooksTelegramByBotTokenError = PostWebhooksTelegramByBotTokenErrors[keyof PostWebhooksTelegramByBotTokenErrors];

export type PostWebhooksTelegramByBotTokenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type IngestTextData = {
    body: IngestTwilioTextInput;
    path?: never;
    query?: never;
    url: '/webhooks/twilio/text';
};

export type IngestTextErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type IngestTextError = IngestTextErrors[keyof IngestTextErrors];

export type IngestTextResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAuthProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/providers';
};

export type GetAuthProvidersErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetAuthProvidersError = GetAuthProvidersErrors[keyof GetAuthProvidersErrors];

export type GetAuthProvidersResponses = {
    /**
     * OK
     */
    200: GetExternalLoginProvidersResult;
};

export type GetAuthProvidersResponse = GetAuthProvidersResponses[keyof GetAuthProvidersResponses];

export type GetAuthExternalByProviderStartData = {
    body?: never;
    path: {
        provider: string;
    };
    query?: {
        returnUrl?: string;
    };
    url: '/auth/external/{provider}/start';
};

export type GetAuthExternalByProviderStartErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetAuthExternalByProviderStartError = GetAuthExternalByProviderStartErrors[keyof GetAuthExternalByProviderStartErrors];

export type GetAuthExternalCallbackData = {
    body?: never;
    path?: never;
    query?: {
        returnUrl?: string;
        remoteError?: string;
    };
    url: '/auth/external-callback';
};

export type GetAuthExternalCallbackErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetAuthExternalCallbackError = GetAuthExternalCallbackErrors[keyof GetAuthExternalCallbackErrors];

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetAuthMeErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetAuthMeError = GetAuthMeErrors[keyof GetAuthMeErrors];

export type GetAuthMeResponses = {
    /**
     * OK
     */
    200: CurrentUserResult;
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAgentsByAgentIdConversationsData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/agents/{agentId}/conversations';
};

export type GetAgentsByAgentIdConversationsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetAgentsByAgentIdConversationsError = GetAgentsByAgentIdConversationsErrors[keyof GetAgentsByAgentIdConversationsErrors];

export type GetAgentsByAgentIdConversationsResponses = {
    /**
     * OK
     */
    200: GetAgentConversationsResult;
};

export type GetAgentsByAgentIdConversationsResponse = GetAgentsByAgentIdConversationsResponses[keyof GetAgentsByAgentIdConversationsResponses];

export type GetAgentsByAgentIdConversationsByConversationIdMessagesData = {
    body?: never;
    path: {
        agentId: string;
        conversationId: string;
    };
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/agents/{agentId}/conversations/{conversationId}/messages';
};

export type GetAgentsByAgentIdConversationsByConversationIdMessagesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetAgentsByAgentIdConversationsByConversationIdMessagesError = GetAgentsByAgentIdConversationsByConversationIdMessagesErrors[keyof GetAgentsByAgentIdConversationsByConversationIdMessagesErrors];

export type GetAgentsByAgentIdConversationsByConversationIdMessagesResponses = {
    /**
     * OK
     */
    200: GetConversationMessagesResult;
};

export type GetAgentsByAgentIdConversationsByConversationIdMessagesResponse = GetAgentsByAgentIdConversationsByConversationIdMessagesResponses[keyof GetAgentsByAgentIdConversationsByConversationIdMessagesResponses];

export type PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadData = {
    body?: never;
    path: {
        agentId: string;
        conversationId: string;
        messageId: string;
    };
    query?: never;
    url: '/agents/{agentId}/conversations/{conversationId}/messages/{messageId}/read';
};

export type PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadError = PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadErrors[keyof PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadErrors];

export type PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadResponses = {
    /**
     * OK
     */
    200: MarkConversationMessageReadResult;
};

export type PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadResponse = PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadResponses[keyof PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadResponses];

export type PatchAgentsByAgentIdConversationsByConversationIdReadData = {
    body?: never;
    path: {
        agentId: string;
        conversationId: string;
    };
    query?: never;
    url: '/agents/{agentId}/conversations/{conversationId}/read';
};

export type PatchAgentsByAgentIdConversationsByConversationIdReadErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PatchAgentsByAgentIdConversationsByConversationIdReadError = PatchAgentsByAgentIdConversationsByConversationIdReadErrors[keyof PatchAgentsByAgentIdConversationsByConversationIdReadErrors];

export type PatchAgentsByAgentIdConversationsByConversationIdReadResponses = {
    /**
     * OK
     */
    200: MarkConversationReadResult;
};

export type PatchAgentsByAgentIdConversationsByConversationIdReadResponse = PatchAgentsByAgentIdConversationsByConversationIdReadResponses[keyof PatchAgentsByAgentIdConversationsByConversationIdReadResponses];
