// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5000/' | (string & {});
};

export type AgeGroup = number;

export type AppInfo = {
    appName: string;
    appVersion: string;
};

export type BoardListItem = {
    id: string;
    name: string;
    ageGroup: AgeGroup;
    voice: null | string;
    language: string;
    producerUserPrompt: null | string;
    evaluatorUserPrompt: null | string;
};

export type CurrentUserResult = {
    id: string;
    email: string;
    displayName: string;
    roles: Array<string>;
};

export type CursorListOfBoardListItem = {
    items?: Array<BoardListItem>;
    hasNextPage?: boolean;
    skip?: number | string;
    take?: number | string;
};

export type CursorListOfStoryListItem = {
    items?: Array<StoryListItem>;
    hasNextPage?: boolean;
    skip?: number | string;
    take?: number | string;
};

export type Figurine = {
    id?: string;
    location?: Point;
};

export type GetStoryMetricsResult = {
    totalPlaytimeSeconds: number | string;
    weekPlaytimeSeconds: number | string;
    storiesCreatedCount: number | string;
    lastCreatedStoryAt: null | string;
};

export type GetStoryResult = {
    id: string;
    title: string;
    status: StoryRequestStatus;
    createdWith: string;
    duration: number | string;
    createdAt: string;
};

export type LoginInput = {
    email: string;
    password: string;
};

export type Point = {
    x?: number | string;
    y?: number | string;
};

export type StoryListItem = {
    id: string;
    title: string;
    status: StoryRequestStatus;
    createdWith: string;
    duration: number | string;
    createdAt: string;
};

export type StoryRequestStatus = 'Processing' | 'Failed' | 'Completed' | 'Canceled';

export type StreamStoryInput = {
    boardId?: string;
    figurines?: Array<Figurine>;
};

export type UpdateBoardInput = {
    name: string;
    ageGroup: AgeGroup;
    voice: null | string;
    language: string;
    producerUserPrompt: null | string;
    evaluatorUserPrompt: null | string;
};

export type UpdateBoardResult = {
    id: string;
    name: string;
    ageGroup: AgeGroup;
    voice: null | string;
    language: string;
    producerUserPrompt: null | string;
    evaluatorUserPrompt: null | string;
};

export type GetAppInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetAppInfoResponses = {
    /**
     * OK
     */
    200: AppInfo;
};

export type GetAppInfoResponse = GetAppInfoResponses[keyof GetAppInfoResponses];

export type GetBoardsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/boards';
};

export type GetBoardsResponses = {
    /**
     * OK
     */
    200: CursorListOfBoardListItem;
};

export type GetBoardsResponse = GetBoardsResponses[keyof GetBoardsResponses];

export type UpdateBoardData = {
    body: UpdateBoardInput;
    path: {
        boardId: string;
    };
    query?: never;
    url: '/boards/{boardId}';
};

export type UpdateBoardErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateBoardResponses = {
    /**
     * OK
     */
    200: UpdateBoardResult;
};

export type UpdateBoardResponse = UpdateBoardResponses[keyof UpdateBoardResponses];

export type GetStoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stories';
};

export type GetStoriesResponses = {
    /**
     * OK
     */
    200: CursorListOfStoryListItem;
};

export type GetStoriesResponse = GetStoriesResponses[keyof GetStoriesResponses];

export type GetStoryMetricsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stories/metrics';
};

export type GetStoryMetricsResponses = {
    /**
     * OK
     */
    200: GetStoryMetricsResult;
};

export type GetStoryMetricsResponse = GetStoryMetricsResponses[keyof GetStoryMetricsResponses];

export type GetStoryData = {
    body?: never;
    path: {
        storyId: string;
    };
    query?: never;
    url: '/stories/{storyId}';
};

export type GetStoryErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetStoryResponses = {
    /**
     * OK
     */
    200: GetStoryResult;
};

export type GetStoryResponse = GetStoryResponses[keyof GetStoryResponses];

export type GetStoryStreamData = {
    body?: never;
    path: {
        storyId: string;
    };
    query?: never;
    url: '/stories/{storyId}/_stream';
};

export type GetStoryStreamResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GenerateStoryStreamData = {
    body: StreamStoryInput;
    path?: never;
    query?: never;
    url: '/stories/_stream';
};

export type GenerateStoryStreamResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAuthLoginData = {
    body: LoginInput;
    path?: never;
    query?: {
        useCookies?: boolean;
        useSessionCookies?: boolean;
    };
    url: '/auth/login';
};

export type PostAuthLoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetAuthMeResponses = {
    /**
     * OK
     */
    200: CurrentUserResult;
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};
