// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getAgentsByAgentIdConversations, getAgentsByAgentIdConversationsByConversationIdMessages, getAppInfo, getAuthExternalCallback, getAuthMe, getAuthProviders, getAuthProvidersByProviderAuthorize, ingestText, type Options, patchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdRead, patchAgentsByAgentIdConversationsByConversationIdRead, postAuthLogout, postWebhooksTelegramByBotToken } from '../sdk.gen';
import type { GetAgentsByAgentIdConversationsByConversationIdMessagesData, GetAgentsByAgentIdConversationsByConversationIdMessagesError, GetAgentsByAgentIdConversationsByConversationIdMessagesResponse, GetAgentsByAgentIdConversationsData, GetAgentsByAgentIdConversationsError, GetAgentsByAgentIdConversationsResponse, GetAppInfoData, GetAppInfoResponse, GetAuthExternalCallbackData, GetAuthExternalCallbackError, GetAuthMeData, GetAuthMeError, GetAuthMeResponse, GetAuthProvidersByProviderAuthorizeData, GetAuthProvidersByProviderAuthorizeError, GetAuthProvidersData, GetAuthProvidersError, GetAuthProvidersResponse, IngestTextData, IngestTextError, PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadData, PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadError, PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadResponse, PatchAgentsByAgentIdConversationsByConversationIdReadData, PatchAgentsByAgentIdConversationsByConversationIdReadError, PatchAgentsByAgentIdConversationsByConversationIdReadResponse, PostAuthLogoutData, PostAuthLogoutError, PostWebhooksTelegramByBotTokenData, PostWebhooksTelegramByBotTokenError } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getAppInfoQueryKey = (options?: Options<GetAppInfoData>) => createQueryKey('getAppInfo', options);

export const getAppInfoOptions = (options?: Options<GetAppInfoData>) => queryOptions<GetAppInfoResponse, DefaultError, GetAppInfoResponse, ReturnType<typeof getAppInfoQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAppInfo({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAppInfoQueryKey(options)
});

export const postWebhooksTelegramByBotTokenMutation = (options?: Partial<Options<PostWebhooksTelegramByBotTokenData>>): UseMutationOptions<unknown, PostWebhooksTelegramByBotTokenError, Options<PostWebhooksTelegramByBotTokenData>> => {
    const mutationOptions: UseMutationOptions<unknown, PostWebhooksTelegramByBotTokenError, Options<PostWebhooksTelegramByBotTokenData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postWebhooksTelegramByBotToken({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const ingestTextMutation = (options?: Partial<Options<IngestTextData>>): UseMutationOptions<unknown, IngestTextError, Options<IngestTextData>> => {
    const mutationOptions: UseMutationOptions<unknown, IngestTextError, Options<IngestTextData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ingestText({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAuthProvidersQueryKey = (options?: Options<GetAuthProvidersData>) => createQueryKey('getAuthProviders', options);

export const getAuthProvidersOptions = (options?: Options<GetAuthProvidersData>) => queryOptions<GetAuthProvidersResponse, GetAuthProvidersError, GetAuthProvidersResponse, ReturnType<typeof getAuthProvidersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAuthProviders({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAuthProvidersQueryKey(options)
});

export const getAuthProvidersByProviderAuthorizeQueryKey = (options: Options<GetAuthProvidersByProviderAuthorizeData>) => createQueryKey('getAuthProvidersByProviderAuthorize', options);

export const getAuthProvidersByProviderAuthorizeOptions = (options: Options<GetAuthProvidersByProviderAuthorizeData>) => queryOptions<unknown, GetAuthProvidersByProviderAuthorizeError, unknown, ReturnType<typeof getAuthProvidersByProviderAuthorizeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAuthProvidersByProviderAuthorize({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAuthProvidersByProviderAuthorizeQueryKey(options)
});

export const getAuthExternalCallbackQueryKey = (options?: Options<GetAuthExternalCallbackData>) => createQueryKey('getAuthExternalCallback', options);

export const getAuthExternalCallbackOptions = (options?: Options<GetAuthExternalCallbackData>) => queryOptions<unknown, GetAuthExternalCallbackError, unknown, ReturnType<typeof getAuthExternalCallbackQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAuthExternalCallback({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAuthExternalCallbackQueryKey(options)
});

export const getAuthMeQueryKey = (options?: Options<GetAuthMeData>) => createQueryKey('getAuthMe', options);

export const getAuthMeOptions = (options?: Options<GetAuthMeData>) => queryOptions<GetAuthMeResponse, GetAuthMeError, GetAuthMeResponse, ReturnType<typeof getAuthMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAuthMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAuthMeQueryKey(options)
});

export const postAuthLogoutMutation = (options?: Partial<Options<PostAuthLogoutData>>): UseMutationOptions<unknown, PostAuthLogoutError, Options<PostAuthLogoutData>> => {
    const mutationOptions: UseMutationOptions<unknown, PostAuthLogoutError, Options<PostAuthLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAgentsByAgentIdConversationsQueryKey = (options: Options<GetAgentsByAgentIdConversationsData>) => createQueryKey('getAgentsByAgentIdConversations', options);

export const getAgentsByAgentIdConversationsOptions = (options: Options<GetAgentsByAgentIdConversationsData>) => queryOptions<GetAgentsByAgentIdConversationsResponse, GetAgentsByAgentIdConversationsError, GetAgentsByAgentIdConversationsResponse, ReturnType<typeof getAgentsByAgentIdConversationsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAgentsByAgentIdConversations({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAgentsByAgentIdConversationsQueryKey(options)
});

export const getAgentsByAgentIdConversationsByConversationIdMessagesQueryKey = (options: Options<GetAgentsByAgentIdConversationsByConversationIdMessagesData>) => createQueryKey('getAgentsByAgentIdConversationsByConversationIdMessages', options);

export const getAgentsByAgentIdConversationsByConversationIdMessagesOptions = (options: Options<GetAgentsByAgentIdConversationsByConversationIdMessagesData>) => queryOptions<GetAgentsByAgentIdConversationsByConversationIdMessagesResponse, GetAgentsByAgentIdConversationsByConversationIdMessagesError, GetAgentsByAgentIdConversationsByConversationIdMessagesResponse, ReturnType<typeof getAgentsByAgentIdConversationsByConversationIdMessagesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAgentsByAgentIdConversationsByConversationIdMessages({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAgentsByAgentIdConversationsByConversationIdMessagesQueryKey(options)
});

export const patchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadMutation = (options?: Partial<Options<PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadData>>): UseMutationOptions<PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadResponse, PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadError, Options<PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadData>> => {
    const mutationOptions: UseMutationOptions<PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadResponse, PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadError, Options<PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdRead({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const patchAgentsByAgentIdConversationsByConversationIdReadMutation = (options?: Partial<Options<PatchAgentsByAgentIdConversationsByConversationIdReadData>>): UseMutationOptions<PatchAgentsByAgentIdConversationsByConversationIdReadResponse, PatchAgentsByAgentIdConversationsByConversationIdReadError, Options<PatchAgentsByAgentIdConversationsByConversationIdReadData>> => {
    const mutationOptions: UseMutationOptions<PatchAgentsByAgentIdConversationsByConversationIdReadResponse, PatchAgentsByAgentIdConversationsByConversationIdReadError, Options<PatchAgentsByAgentIdConversationsByConversationIdReadData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchAgentsByAgentIdConversationsByConversationIdRead({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
