services:
  initializer:
    image: 'europe-west10-docker.pkg.dev/econduct/dev-docker/shelfbuddy-initializer:${IMAGE_TAG:-latest}'
    restart: 'no'
    environment:
      - 'ConnectionStrings__shelfbuddy=${DATABASE_URL}'
      - 'ConnectionStrings__rabbitmq=${RABBITMQ_URL}'
      - 'PUBLIC_BASE_URL=${PUBLIC_BASE_URL}'
      - 'TELEGRAM_SECRET_TOKEN=${TELEGRAM_SECRET_TOKEN}'
      - 'RABBITMQ_MANAGEMENTURL=${RABBITMQ_MANAGEMENTURL}'
      - 'RABBITMQ_USER=${RABBITMQ_USER}'
      - 'RABBITMQ_PASS=${RABBITMQ_PASS}'
      - 'RABBITMQ_VHOST=${RABBITMQ_VHOST}'
    networks:
      - coolify
      - default
  webapi:
    image: 'europe-west10-docker.pkg.dev/econduct/dev-docker/shelfbuddy-webapi:${IMAGE_TAG:-latest}'
    environment:
      - 'ConnectionStrings__shelfbuddy=${DATABASE_URL}'
      - 'ConnectionStrings__rabbitmq=${RABBITMQ_URL}'
      - 'SWAGGER_ENABLED=${SWAGGER_ENABLED}'
      - 'PUBLIC_BASE_URL=${PUBLIC_BASE_URL}'
      - 'TELEGRAM_SECRET_TOKEN=${TELEGRAM_SECRET_TOKEN}'
      - 'AUTH_GOOGLE_CLIENT_ID=${AUTH_GOOGLE_CLIENT_ID}'
      - 'AUTH_GOOGLE_CLIENT_SECRET=${AUTH_GOOGLE_CLIENT_SECRET}'
      - 'AUTH_SQUARE_CLIENT_ID=${AUTH_SQUARE_CLIENT_ID}'
      - 'AUTH_SQUARE_CLIENT_SECRET=${AUTH_SQUARE_CLIENT_SECRET}'
      - 'SQUARE_CLIENT_ID=${SQUARE_CLIENT_ID}'
      - 'SQUARE_CLIENT_SECRET=${SQUARE_CLIENT_SECRET}'
    healthcheck:
      test: 'wget --no-verbose --tries=1 --spider http://localhost:5000/health || exit 1'
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      initializer:
        condition: service_completed_successfully
    networks:
      - coolify
      - default
  webapp:
    image: 'europe-west10-docker.pkg.dev/econduct/dev-docker/shelfbuddy-webapp:${IMAGE_TAG:-latest}'
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
      - KEEP_ALIVE_TIMEOUT=70000
    healthcheck:
      test: 'wget --no-verbose --tries=1 --spider http://127.0.0.1:5010/health || exit 1'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    depends_on:
      webapi:
        condition: service_started
    networks:
      - coolify
      - default
    labels:
      - traefik.enable=true
      - traefik.http.services.webapp-kokcgwwwgko88wk4w4ccw440.loadbalancer.server.port=5010
      - traefik.http.services.webapp-kokcgwwwgko88wk4w4ccw440.loadbalancer.server.scheme=http
      - traefik.http.services.webapp-kokcgwwwgko88wk4w4ccw440.loadbalancer.passhostheader=true
      - traefik.http.services.webapp-kokcgwwwgko88wk4w4ccw440.loadbalancer.responseforwarding.flushinterval=100ms
      - traefik.http.routers.webapp-kokcgwwwgko88wk4w4ccw440.rule=Host(`shelfbuddy.dev.econduct.de`)
      - traefik.http.routers.webapp-kokcgwwwgko88wk4w4ccw440.entrypoints=https
      - traefik.http.routers.webapp-kokcgwwwgko88wk4w4ccw440.tls.certresolver=letsencrypt
      - traefik.docker.network=coolify
networks:
  coolify:
    external: true
