services:
  webapp:
    image: 'europe-west10-docker.pkg.dev/econduct/dev-docker/shelfbuddy-webapp:${IMAGE_TAG:-latest}'
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
      - KEEP_ALIVE_TIMEOUT=70000
    healthcheck:
      test: 'wget --no-verbose --tries=1 --spider http://127.0.0.1:5010/health || exit 1'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - coolify
      - default
    labels:
      - traefik.enable=true
      - traefik.http.services.webapp-kokcgwwwgko88wk4w4ccw440.loadbalancer.server.port=5010
      - traefik.http.services.webapp-kokcgwwwgko88wk4w4ccw440.loadbalancer.server.scheme=http
      - traefik.http.services.webapp-kokcgwwwgko88wk4w4ccw440.loadbalancer.passhostheader=true
      - traefik.http.services.webapp-kokcgwwwgko88wk4w4ccw440.loadbalancer.responseforwarding.flushinterval=100ms
      - traefik.http.routers.webapp-kokcgwwwgko88wk4w4ccw440.rule=Host(`shelfbuddy.dev.econduct.de`)
      - traefik.http.routers.webapp-kokcgwwwgko88wk4w4ccw440.entrypoints=https
      - traefik.http.routers.webapp-kokcgwwwgko88wk4w4ccw440.tls.certresolver=letsencrypt
      - traefik.docker.network=coolify
networks:
  coolify:
    external: true
