// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShelfBuddy.Data;

#nullable disable

namespace ShelfBuddy.Initializer.Migrations
{
    [DbContext(typeof(MainDataContext))]
    partial class MainDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_data_protection_keys");

                    b.ToTable("srbd_data_protection_keys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("srbd_ix_srbd_asp_net_role_claims_role_id");

                    b.ToTable("srbd_asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("srbd_ix_srbd_asp_net_user_claims_user_id");

                    b.ToTable("srbd_asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("srbd_pk_srbd_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("srbd_ix_srbd_asp_net_user_logins_user_id");

                    b.ToTable("srbd_asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId")
                        .HasName("srbd_pk_srbd_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("srbd_ix_srbd_asp_net_user_roles_role_id");

                    b.ToTable("srbd_asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("srbd_pk_srbd_asp_net_user_tokens");

                    b.ToTable("srbd_asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Personality")
                        .HasColumnType("integer");

                    b.Property<string>("PersonalityPromptRaw")
                        .HasColumnType("text");

                    b.Property<string>("PersonalityPromptSanitized")
                        .HasColumnType("text");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TelegramBotToken")
                        .HasColumnType("text");

                    b.Property<string>("TwilioPhoneNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WhatsappNumber")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_agents");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("srbd_ix_srbd_agents_subscription_id");

                    b.HasIndex("TelegramBotToken")
                        .IsUnique()
                        .HasDatabaseName("srbd_ix_srbd_agents_telegram_bot_token")
                        .HasFilter("\"TelegramBotToken\" IS NOT NULL");

                    b.HasIndex("TwilioPhoneNumber")
                        .HasDatabaseName("srbd_ix_srbd_agents_twilio_phone_number")
                        .HasFilter("\"TwilioPhoneNumber\" IS NOT NULL");

                    b.HasIndex("WhatsappNumber")
                        .HasDatabaseName("srbd_ix_srbd_agents_whatsapp_number")
                        .HasFilter("\"WhatsappNumber\" IS NOT NULL");

                    b.ToTable("srbd_agents");
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("srbd_role_name_index");

                    b.ToTable("srbd_asp_net_roles", (string)null);
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("srbd_email_index");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("srbd_user_name_index");

                    b.ToTable("srbd_asp_net_users", (string)null);
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastMessagePreview")
                        .HasColumnType("text");

                    b.Property<int?>("LastMessageRole")
                        .HasColumnType("integer");

                    b.Property<string>("ParticipantExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_conversations");

                    b.HasIndex("AgentId", "UnreadCount")
                        .HasDatabaseName("srbd_ix_srbd_conversations_agent_id_unread_count");

                    b.HasIndex("AgentId", "LastMessageAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("srbd_ix_srbd_conversations_agent_id_last_message_at_id");

                    b.HasIndex("AgentId", "ParticipantExternalId", "Channel")
                        .IsUnique()
                        .HasDatabaseName("srbd_ix_srbd_conversations_agent_id_participant_external_id_channel");

                    b.ToTable("srbd_conversations");
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_conversation_messages");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("srbd_ix_srbd_conversation_messages_agent_id");

                    b.HasIndex("ConversationId", "IsRead", "Role")
                        .HasDatabaseName("srbd_ix_srbd_conversation_messages_conversation_id_is_read_role");

                    b.HasIndex("ConversationId", "OccurredAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("srbd_ix_srbd_conversation_messages_conversation_id_occurred_at_id");

                    b.ToTable("srbd_conversation_messages");
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.CreditTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("StripeEventId")
                        .HasColumnType("text");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_credit_transactions");

                    b.HasIndex("StripeEventId")
                        .IsUnique()
                        .HasDatabaseName("srbd_ix_srbd_credit_transactions_stripe_event_id");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("srbd_ix_srbd_credit_transactions_subscription_id");

                    b.ToTable("srbd_credit_transactions");
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.Property<string>("StripePriceId")
                        .HasColumnType("text");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("text");

                    b.Property<int>("SubscriptionCreditBalance")
                        .HasColumnType("integer");

                    b.Property<int>("TopUpCreditBalance")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_subscriptions");

                    b.ToTable("srbd_subscriptions");
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.SubscriptionOnboardingState", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PrimaryAgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubscriptionId")
                        .HasName("srbd_pk_srbd_subscription_onboarding_states");

                    b.HasIndex("PrimaryAgentId")
                        .HasDatabaseName("srbd_ix_srbd_subscription_onboarding_states_primary_agent_id");

                    b.HasIndex("SubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("srbd_ix_srbd_subscription_onboarding_states_subscription_id");

                    b.ToTable("srbd_subscription_onboarding_states");
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.SubscriptionOnboardingStepState", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Step")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SkippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubscriptionId", "Step")
                        .HasName("srbd_pk_srbd_subscription_onboarding_step_states");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("srbd_ix_srbd_subscription_onboarding_step_states_subscription_id");

                    b.ToTable("srbd_subscription_onboarding_step_states");
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.SubscriptionSquareConnection", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AccessTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConnectedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DisconnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedAccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SquareMerchantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubscriptionId")
                        .HasName("srbd_pk_srbd_subscription_square_connections");

                    b.HasIndex("ConnectedByUserId")
                        .HasDatabaseName("srbd_ix_srbd_subscription_square_connections_connected_by_user_id");

                    b.HasIndex("SquareMerchantId")
                        .HasDatabaseName("srbd_ix_srbd_subscription_square_connections_square_merchant_id");

                    b.HasIndex("SubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("srbd_ix_srbd_subscription_square_connections_subscription_id");

                    b.ToTable("srbd_subscription_square_connections");
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.SubscriptionUser", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubscriptionId", "UserId")
                        .HasName("srbd_pk_srbd_subscription_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("srbd_ix_srbd_subscription_users_user_id");

                    b.ToTable("srbd_subscription_users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("ShelfBuddy.Data.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ShelfBuddy.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ShelfBuddy.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("ShelfBuddy.Data.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("ShelfBuddy.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ShelfBuddy.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.Agent", b =>
                {
                    b.HasOne("ShelfBuddy.Data.Entities.Subscription", "Subscription")
                        .WithMany("Agents")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_agents_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.Conversation", b =>
                {
                    b.HasOne("ShelfBuddy.Data.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_conversations_srbd_agents_agent_id");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.ConversationMessage", b =>
                {
                    b.HasOne("ShelfBuddy.Data.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_conversation_messages_srbd_agents_agent_id");

                    b.HasOne("ShelfBuddy.Data.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_conversation_messages_srbd_conversations_conversation_id");

                    b.Navigation("Agent");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.CreditTransaction", b =>
                {
                    b.HasOne("ShelfBuddy.Data.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_credit_transactions_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.SubscriptionOnboardingState", b =>
                {
                    b.HasOne("ShelfBuddy.Data.Entities.Agent", "PrimaryAgent")
                        .WithMany()
                        .HasForeignKey("PrimaryAgentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("srbd_fk_srbd_subscription_onboarding_states_srbd_agents_primary_agen~");

                    b.HasOne("ShelfBuddy.Data.Entities.Subscription", "Subscription")
                        .WithOne("OnboardingState")
                        .HasForeignKey("ShelfBuddy.Data.Entities.SubscriptionOnboardingState", "SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_subscription_onboarding_states_srbd_subscriptions_subs~");

                    b.Navigation("PrimaryAgent");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.SubscriptionOnboardingStepState", b =>
                {
                    b.HasOne("ShelfBuddy.Data.Entities.Subscription", "Subscription")
                        .WithMany("OnboardingStepStates")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_subscription_onboarding_step_states_srbd_subscriptions~");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.SubscriptionSquareConnection", b =>
                {
                    b.HasOne("ShelfBuddy.Data.Entities.ApplicationUser", "ConnectedByUser")
                        .WithMany()
                        .HasForeignKey("ConnectedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_subscription_square_connections_srbd_asp_net_users_con~");

                    b.HasOne("ShelfBuddy.Data.Entities.Subscription", "Subscription")
                        .WithOne("SquareConnection")
                        .HasForeignKey("ShelfBuddy.Data.Entities.SubscriptionSquareConnection", "SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_subscription_square_connections_srbd_subscriptions_sub~");

                    b.Navigation("ConnectedByUser");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.SubscriptionUser", b =>
                {
                    b.HasOne("ShelfBuddy.Data.Entities.Subscription", "Subscription")
                        .WithMany("SubscriptionUsers")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_subscription_users_srbd_subscriptions_subscription_id");

                    b.HasOne("ShelfBuddy.Data.Entities.ApplicationUser", "User")
                        .WithMany("SubscriptionUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_subscription_users_srbd_asp_net_users_user_id");

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("SubscriptionUsers");
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ShelfBuddy.Data.Entities.Subscription", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("OnboardingState");

                    b.Navigation("OnboardingStepStates");

                    b.Navigation("SquareConnection");

                    b.Navigation("SubscriptionUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
