import Image from 'next/image'
import "../globals.css";
import { Logo } from '../../../public/Logo';
import Link from 'next/link';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen m-0 bg-white text-neutral-900 font-sans">

        {/* Left Section: Marketing Image & Copy (Hidden on Mobile) */}
        <div className="hidden lg:flex lg:w-1/2 relative bg-neutral-900 overflow-hidden">
          {/* Abstract/Marketing Background Image */}
          <Image
            src="/photo-1556742049-0cfed4f6a45d.jfif"
            alt="Storefront checkout"
            width={1200}
            height={800}
            className="absolute inset-0 w-full h-full object-cover opacity-30 mix-blend-overlay grayscale" />

          <div className="relative z-10 flex flex-col justify-between p-12 lg:p-24 w-full">
            <Link href="/" className="text-2xl font-bold tracking-tight text-white">Hey<span className="text-neutral-400">Alan</span></Link>

            <div className="max-w-md">
              <h1 className="text-4xl font-extrabold text-white mb-6 leading-tight">
                Conversational Sales for your Square.
              </h1>
              <p className="text-neutral-300 text-lg leading-relaxed">
                An autonomous AI agent that knows your inventory. Engage customers via Text, WhatsApp, and Telegram. Drive upsells, process payments, and schedule shipping &mdash; all through natural language.
              </p>
            </div>

            <div className="text-sm text-neutral-400">
             &nbsp; {/* &copy; 2026 HeyAlan. All rights reserved. Not affiliated with Block, Inc. */}
            </div>
          </div>
        </div>

        {/* Right Section: Login Interface */}
        <div className="w-full lg:w-1/2 flex flex-col min-h-screen relative">

          {/* Mobile Header (Only visible on small screens) */}
          <header className="h-20 flex items-center px-8 shrink-0 lg:hidden">
            <Link href="/" className="text-xl font-bold tracking-tight">Hey<span className="text-neutral-500">Alan</span></Link>
          </header>

          {/* Main Login Content */}
          <main className="flex-1 flex flex-col justify-center px-8 lg:px-16">
            {children}
          </main>

          {/* Footer / Terms & Privacy */}
          <footer className="py-8 px-8 text-center text-sm text-neutral-500 shrink-0">
            By proceeding, you agree to our{" "}
            <a href="/terms" className="font-medium text-neutral-700 underline underline-offset-4 hover:text-neutral-900 transition-colors">Terms of Service</a>{" "}and{" "}
            <a href="/privacy" className="font-medium text-neutral-700 underline underline-offset-4 hover:text-neutral-900 transition-colors">Privacy Policy</a>.
          </footer>

        </div>

      </body>
    </html>
  )
}
