import Link from "next/link";
import "../globals.css";
import { OnboardingShell } from "./onboarding-shell";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen m-0">
        <header className="h-20 flex items-center px-6 shrink-0">
          <Link href="/" className="text-xl font-bold tracking-tight"><span className="text-zinc-500">Hey</span>Alan</Link>
        </header>
        <main className="flex-1 flex flex-col justify-center">
          <div className="max-w-xl mx-auto text-center p-6 w-full ">
            <OnboardingShell>{children}</OnboardingShell>
          </div>
        </main>
      </body>
    </html>
  )
}
