// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { generateStoryStream, getAppInfo, getAuthMe, getBoards, getStories, getStory, getStoryMetrics, getStoryStream, type Options, postAuthLogin, postAuthLogout, updateBoard } from '../sdk.gen';
import type { GenerateStoryStreamData, GetAppInfoData, GetAppInfoResponse, GetAuthMeData, GetAuthMeResponse, GetBoardsData, GetBoardsResponse, GetStoriesData, GetStoriesResponse, GetStoryData, GetStoryMetricsData, GetStoryMetricsResponse, GetStoryResponse, GetStoryStreamData, PostAuthLoginData, PostAuthLogoutData, UpdateBoardData, UpdateBoardResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getAppInfoQueryKey = (options?: Options<GetAppInfoData>) => createQueryKey('getAppInfo', options);

export const getAppInfoOptions = (options?: Options<GetAppInfoData>) => queryOptions<GetAppInfoResponse, DefaultError, GetAppInfoResponse, ReturnType<typeof getAppInfoQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAppInfo({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAppInfoQueryKey(options)
});

export const getBoardsQueryKey = (options?: Options<GetBoardsData>) => createQueryKey('getBoards', options);

export const getBoardsOptions = (options?: Options<GetBoardsData>) => queryOptions<GetBoardsResponse, DefaultError, GetBoardsResponse, ReturnType<typeof getBoardsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getBoards({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBoardsQueryKey(options)
});

export const updateBoardMutation = (options?: Partial<Options<UpdateBoardData>>): UseMutationOptions<UpdateBoardResponse, DefaultError, Options<UpdateBoardData>> => {
    const mutationOptions: UseMutationOptions<UpdateBoardResponse, DefaultError, Options<UpdateBoardData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateBoard({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getStoriesQueryKey = (options?: Options<GetStoriesData>) => createQueryKey('getStories', options);

export const getStoriesOptions = (options?: Options<GetStoriesData>) => queryOptions<GetStoriesResponse, DefaultError, GetStoriesResponse, ReturnType<typeof getStoriesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStories({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStoriesQueryKey(options)
});

export const getStoryMetricsQueryKey = (options?: Options<GetStoryMetricsData>) => createQueryKey('getStoryMetrics', options);

export const getStoryMetricsOptions = (options?: Options<GetStoryMetricsData>) => queryOptions<GetStoryMetricsResponse, DefaultError, GetStoryMetricsResponse, ReturnType<typeof getStoryMetricsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStoryMetrics({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStoryMetricsQueryKey(options)
});

export const getStoryQueryKey = (options: Options<GetStoryData>) => createQueryKey('getStory', options);

export const getStoryOptions = (options: Options<GetStoryData>) => queryOptions<GetStoryResponse, DefaultError, GetStoryResponse, ReturnType<typeof getStoryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStory({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStoryQueryKey(options)
});

export const getStoryStreamQueryKey = (options: Options<GetStoryStreamData>) => createQueryKey('getStoryStream', options);

export const getStoryStreamOptions = (options: Options<GetStoryStreamData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getStoryStreamQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStoryStream({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStoryStreamQueryKey(options)
});

export const generateStoryStreamMutation = (options?: Partial<Options<GenerateStoryStreamData>>): UseMutationOptions<unknown, DefaultError, Options<GenerateStoryStreamData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<GenerateStoryStreamData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await generateStoryStream({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postAuthLoginMutation = (options?: Partial<Options<PostAuthLoginData>>): UseMutationOptions<unknown, DefaultError, Options<PostAuthLoginData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostAuthLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAuthMeQueryKey = (options?: Options<GetAuthMeData>) => createQueryKey('getAuthMe', options);

export const getAuthMeOptions = (options?: Options<GetAuthMeData>) => queryOptions<GetAuthMeResponse, DefaultError, GetAuthMeResponse, ReturnType<typeof getAuthMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAuthMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAuthMeQueryKey(options)
});

export const postAuthLogoutMutation = (options?: Partial<Options<PostAuthLogoutData>>): UseMutationOptions<unknown, DefaultError, Options<PostAuthLogoutData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostAuthLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
