// <auto-generated />
using System;
using HeyAlan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HeyAlan.Initializer.Migrations
{
    [DbContext(typeof(MainDataContext))]
    partial class MainDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("WolverineEnabled", "true");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HeyAlan.Data.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Personality")
                        .HasColumnType("integer");

                    b.Property<string>("PersonalityPromptRaw")
                        .HasColumnType("text");

                    b.Property<string>("PersonalityPromptSanitized")
                        .HasColumnType("text");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TelegramBotToken")
                        .HasColumnType("text");

                    b.Property<string>("TwilioPhoneNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WhatsappNumber")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_agents");

                    b.HasAlternateKey("SubscriptionId", "Id")
                        .HasName("srbd_ak_srbd_agents_subscription_id_id");

                    b.HasIndex("TelegramBotToken")
                        .IsUnique()
                        .HasDatabaseName("srbd_ix_srbd_agents_telegram_bot_token")
                        .HasFilter("\"TelegramBotToken\" IS NOT NULL");

                    b.HasIndex("TwilioPhoneNumber")
                        .HasDatabaseName("srbd_ix_srbd_agents_twilio_phone_number")
                        .HasFilter("\"TwilioPhoneNumber\" IS NOT NULL");

                    b.HasIndex("WhatsappNumber")
                        .HasDatabaseName("srbd_ix_srbd_agents_whatsapp_number")
                        .HasFilter("\"WhatsappNumber\" IS NOT NULL");

                    b.ToTable("srbd_agents");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.AgentCatalogProductAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubscriptionCatalogProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_agent_catalog_product_accesses");

                    b.HasIndex("SubscriptionId", "AgentId", "Id")
                        .HasDatabaseName("srbd_ix_agent_catalog_access_agent");

                    b.HasIndex("SubscriptionId", "AgentId", "SubscriptionCatalogProductId")
                        .IsUnique()
                        .HasDatabaseName("srbd_ix_agent_catalog_access_agent_product");

                    b.HasIndex("SubscriptionId", "SubscriptionCatalogProductId", "AgentId")
                        .HasDatabaseName("srbd_ix_agent_catalog_access_product");

                    b.ToTable("srbd_agent_catalog_product_accesses");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.AgentSalesZipCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ZipCodeNormalized")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_agent_sales_zip_codes");

                    b.HasIndex("SubscriptionId", "AgentId", "Id")
                        .HasDatabaseName("srbd_ix_agent_sales_zip_agent");

                    b.HasIndex("SubscriptionId", "AgentId", "ZipCodeNormalized")
                        .IsUnique()
                        .HasDatabaseName("srbd_ix_agent_sales_zip_agent_zip");

                    b.ToTable("srbd_agent_sales_zip_codes");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("srbd_role_name_index");

                    b.ToTable("srbd_asp_net_roles", (string)null);
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("srbd_email_index");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("srbd_user_name_index");

                    b.ToTable("srbd_asp_net_users", (string)null);
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastMessagePreview")
                        .HasColumnType("text");

                    b.Property<int?>("LastMessageRole")
                        .HasColumnType("integer");

                    b.Property<string>("ParticipantExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_conversations");

                    b.HasIndex("AgentId", "UnreadCount")
                        .HasDatabaseName("srbd_ix_srbd_conversations_agent_id_unread_count");

                    b.HasIndex("AgentId", "LastMessageAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("srbd_ix_srbd_conversations_agent_id_last_message_at_id");

                    b.HasIndex("AgentId", "ParticipantExternalId", "Channel")
                        .IsUnique()
                        .HasDatabaseName("srbd_ix_srbd_conversations_agent_id_participant_external_id_channel");

                    b.ToTable("srbd_conversations");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_conversation_messages");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("srbd_ix_srbd_conversation_messages_agent_id");

                    b.HasIndex("ConversationId", "IsRead", "Role")
                        .HasDatabaseName("srbd_ix_srbd_conversation_messages_conversation_id_is_read_role");

                    b.HasIndex("ConversationId", "OccurredAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("srbd_ix_srbd_conversation_messages_conversation_id_occurred_at_id");

                    b.ToTable("srbd_conversation_messages");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.CreditTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("StripeEventId")
                        .HasColumnType("text");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_credit_transactions");

                    b.HasIndex("StripeEventId")
                        .IsUnique()
                        .HasDatabaseName("srbd_ix_srbd_credit_transactions_stripe_event_id");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("srbd_ix_srbd_credit_transactions_subscription_id");

                    b.ToTable("srbd_credit_transactions");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.SquareWebhookReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_square_webhook_receipts");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("srbd_ix_srbd_square_webhook_receipts_event_id");

                    b.HasIndex("SubscriptionId", "IsProcessed", "ReceivedAtUtc")
                        .HasDatabaseName("srbd_ix_srbd_square_webhook_receipts_subscription_id_is_processed_rec~");

                    b.HasIndex("SubscriptionId", "ReceivedAtUtc", "Id")
                        .HasDatabaseName("srbd_ix_srbd_square_webhook_receipts_subscription_id_received_at_utc_id");

                    b.ToTable("srbd_square_webhook_receipts");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.Property<string>("StripePriceId")
                        .HasColumnType("text");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("text");

                    b.Property<int>("SubscriptionCreditBalance")
                        .HasColumnType("integer");

                    b.Property<int>("TopUpCreditBalance")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_subscriptions");

                    b.ToTable("srbd_subscriptions");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.SubscriptionCatalogProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("BasePriceAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("BasePriceCurrency")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSellable")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.Property<string>("SquareItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SquareUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SquareVariationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("SquareVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VariationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_subscription_catalog_products");

                    b.HasAlternateKey("SubscriptionId", "Id")
                        .HasName("srbd_ak_srbd_subscription_catalog_products_subscription_id_id");

                    b.HasIndex("SubscriptionId", "SearchText")
                        .HasDatabaseName("srbd_ix_catalog_product_subscription_search");

                    b.HasIndex("SubscriptionId", "SquareItemId")
                        .HasDatabaseName("srbd_ix_catalog_product_subscription_item");

                    b.HasIndex("SubscriptionId", "SquareVariationId")
                        .IsUnique()
                        .HasDatabaseName("srbd_ix_catalog_product_subscription_variation");

                    b.HasIndex("SubscriptionId", "IsDeleted", "IsSellable", "ItemName", "Id")
                        .HasDatabaseName("srbd_ix_catalog_product_subscription_active_name");

                    b.ToTable("srbd_subscription_catalog_products");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.SubscriptionCatalogProductLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAvailableForSale")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSoldOut")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("PriceOverrideAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("PriceOverrideCurrency")
                        .HasColumnType("text");

                    b.Property<string>("SquareVariationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubscriptionCatalogProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_subscription_catalog_product_locations");

                    b.HasIndex("SubscriptionId", "SubscriptionCatalogProductId")
                        .HasDatabaseName("srbd_ix_catalog_product_location_product");

                    b.HasIndex("SubscriptionId", "LocationId", "Id")
                        .HasDatabaseName("srbd_ix_catalog_product_location_location");

                    b.HasIndex("SubscriptionId", "SquareVariationId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("srbd_ix_catalog_product_location_variation_location");

                    b.ToTable("srbd_subscription_catalog_product_locations");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.SubscriptionCatalogSyncState", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorCode")
                        .HasColumnType("text");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSyncCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSyncStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSyncedBeginTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastTriggerSource")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NextScheduledSyncAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PendingResync")
                        .HasColumnType("boolean");

                    b.Property<bool>("SyncInProgress")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubscriptionId")
                        .HasName("srbd_pk_srbd_subscription_catalog_sync_states");

                    b.HasIndex("SubscriptionId", "NextScheduledSyncAtUtc")
                        .HasDatabaseName("srbd_ix_srbd_subscription_catalog_sync_states_subscription_id_next_sc~");

                    b.ToTable("srbd_subscription_catalog_sync_states");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.SubscriptionOnboardingState", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PrimaryAgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubscriptionId")
                        .HasName("srbd_pk_srbd_subscription_onboarding_states");

                    b.HasIndex("PrimaryAgentId")
                        .HasDatabaseName("srbd_ix_srbd_subscription_onboarding_states_primary_agent_id");

                    b.HasIndex("SubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("srbd_ix_srbd_subscription_onboarding_states_subscription_id");

                    b.ToTable("srbd_subscription_onboarding_states");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.SubscriptionSquareConnection", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AccessTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConnectedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DisconnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedAccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SquareMerchantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubscriptionId")
                        .HasName("srbd_pk_srbd_subscription_square_connections");

                    b.HasIndex("ConnectedByUserId")
                        .HasDatabaseName("srbd_ix_srbd_subscription_square_connections_connected_by_user_id");

                    b.HasIndex("SquareMerchantId")
                        .HasDatabaseName("srbd_ix_srbd_subscription_square_connections_square_merchant_id");

                    b.HasIndex("SubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("srbd_ix_srbd_subscription_square_connections_subscription_id");

                    b.ToTable("srbd_subscription_square_connections");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.SubscriptionUser", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubscriptionId", "UserId")
                        .HasName("srbd_pk_srbd_subscription_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("srbd_ix_srbd_subscription_users_user_id");

                    b.ToTable("srbd_subscription_users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_data_protection_keys");

                    b.ToTable("srbd_data_protection_keys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("srbd_ix_srbd_asp_net_role_claims_role_id");

                    b.ToTable("srbd_asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("srbd_pk_srbd_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("srbd_ix_srbd_asp_net_user_claims_user_id");

                    b.ToTable("srbd_asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("srbd_pk_srbd_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("srbd_ix_srbd_asp_net_user_logins_user_id");

                    b.ToTable("srbd_asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId")
                        .HasName("srbd_pk_srbd_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("srbd_ix_srbd_asp_net_user_roles_role_id");

                    b.ToTable("srbd_asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("srbd_pk_srbd_asp_net_user_tokens");

                    b.ToTable("srbd_asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("text")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("wolverine_incoming_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.ToTable("wolverine_outgoing_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.Agent", b =>
                {
                    b.HasOne("HeyAlan.Data.Entities.Subscription", "Subscription")
                        .WithMany("Agents")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_agents_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.AgentCatalogProductAccess", b =>
                {
                    b.HasOne("HeyAlan.Data.Entities.Agent", "Agent")
                        .WithMany("CatalogProductAccesses")
                        .HasForeignKey("SubscriptionId", "AgentId")
                        .HasPrincipalKey("SubscriptionId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_agent_catalog_access_agent");

                    b.HasOne("HeyAlan.Data.Entities.SubscriptionCatalogProduct", "SubscriptionCatalogProduct")
                        .WithMany("AgentProductAccesses")
                        .HasForeignKey("SubscriptionId", "SubscriptionCatalogProductId")
                        .HasPrincipalKey("SubscriptionId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_agent_catalog_access_product");

                    b.Navigation("Agent");

                    b.Navigation("SubscriptionCatalogProduct");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.AgentSalesZipCode", b =>
                {
                    b.HasOne("HeyAlan.Data.Entities.Agent", "Agent")
                        .WithMany("SalesZipCodes")
                        .HasForeignKey("SubscriptionId", "AgentId")
                        .HasPrincipalKey("SubscriptionId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_agent_sales_zip_agent");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.Conversation", b =>
                {
                    b.HasOne("HeyAlan.Data.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_conversations_srbd_agents_agent_id");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.ConversationMessage", b =>
                {
                    b.HasOne("HeyAlan.Data.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_conversation_messages_srbd_agents_agent_id");

                    b.HasOne("HeyAlan.Data.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_conversation_messages_srbd_conversations_conversation_id");

                    b.Navigation("Agent");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.CreditTransaction", b =>
                {
                    b.HasOne("HeyAlan.Data.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_credit_transactions_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.SquareWebhookReceipt", b =>
                {
                    b.HasOne("HeyAlan.Data.Entities.Subscription", "Subscription")
                        .WithMany("SquareWebhookReceipts")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_square_webhook_receipt_subscription");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.SubscriptionCatalogProduct", b =>
                {
                    b.HasOne("HeyAlan.Data.Entities.Subscription", "Subscription")
                        .WithMany("CatalogProducts")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_catalog_product_subscription");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.SubscriptionCatalogProductLocation", b =>
                {
                    b.HasOne("HeyAlan.Data.Entities.Subscription", "Subscription")
                        .WithMany("CatalogProductLocations")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_catalog_product_location_subscription");

                    b.HasOne("HeyAlan.Data.Entities.SubscriptionCatalogProduct", "SubscriptionCatalogProduct")
                        .WithMany("Locations")
                        .HasForeignKey("SubscriptionId", "SubscriptionCatalogProductId")
                        .HasPrincipalKey("SubscriptionId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_catalog_product_location_product");

                    b.Navigation("Subscription");

                    b.Navigation("SubscriptionCatalogProduct");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.SubscriptionCatalogSyncState", b =>
                {
                    b.HasOne("HeyAlan.Data.Entities.Subscription", "Subscription")
                        .WithOne("CatalogSyncState")
                        .HasForeignKey("HeyAlan.Data.Entities.SubscriptionCatalogSyncState", "SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_subscription_catalog_sync_state_subscription");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.SubscriptionOnboardingState", b =>
                {
                    b.HasOne("HeyAlan.Data.Entities.Agent", "PrimaryAgent")
                        .WithMany()
                        .HasForeignKey("PrimaryAgentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("srbd_fk_srbd_subscription_onboarding_states_srbd_agents_primary_agen~");

                    b.HasOne("HeyAlan.Data.Entities.Subscription", "Subscription")
                        .WithOne("OnboardingState")
                        .HasForeignKey("HeyAlan.Data.Entities.SubscriptionOnboardingState", "SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_subscription_onboarding_states_srbd_subscriptions_subs~");

                    b.Navigation("PrimaryAgent");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.SubscriptionSquareConnection", b =>
                {
                    b.HasOne("HeyAlan.Data.Entities.ApplicationUser", "ConnectedByUser")
                        .WithMany()
                        .HasForeignKey("ConnectedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_subscription_square_connections_srbd_asp_net_users_con~");

                    b.HasOne("HeyAlan.Data.Entities.Subscription", "Subscription")
                        .WithOne("SquareConnection")
                        .HasForeignKey("HeyAlan.Data.Entities.SubscriptionSquareConnection", "SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_subscription_square_connections_srbd_subscriptions_sub~");

                    b.Navigation("ConnectedByUser");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.SubscriptionUser", b =>
                {
                    b.HasOne("HeyAlan.Data.Entities.Subscription", "Subscription")
                        .WithMany("SubscriptionUsers")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_subscription_users_srbd_subscriptions_subscription_id");

                    b.HasOne("HeyAlan.Data.Entities.ApplicationUser", "User")
                        .WithMany("SubscriptionUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_subscription_users_srbd_asp_net_users_user_id");

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("HeyAlan.Data.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_asp_net_role_claims_srbd_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("HeyAlan.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_asp_net_user_claims_srbd_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("HeyAlan.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_asp_net_user_logins_srbd_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("HeyAlan.Data.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_asp_net_user_roles_srbd_asp_net_roles_role_id");

                    b.HasOne("HeyAlan.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_asp_net_user_roles_srbd_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("HeyAlan.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("srbd_fk_srbd_asp_net_user_tokens_srbd_asp_net_users_user_id");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.Agent", b =>
                {
                    b.Navigation("CatalogProductAccesses");

                    b.Navigation("SalesZipCodes");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("SubscriptionUsers");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.Subscription", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("CatalogProductLocations");

                    b.Navigation("CatalogProducts");

                    b.Navigation("CatalogSyncState");

                    b.Navigation("OnboardingState");

                    b.Navigation("SquareConnection");

                    b.Navigation("SquareWebhookReceipts");

                    b.Navigation("SubscriptionUsers");
                });

            modelBuilder.Entity("HeyAlan.Data.Entities.SubscriptionCatalogProduct", b =>
                {
                    b.Navigation("AgentProductAccesses");

                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
