// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SquareBuddy.Data;

#nullable disable

namespace SquareBuddy.Initializer.Migrations
{
    [DbContext(typeof(MainDataContext))]
    partial class MainDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("sb_pk_sb_data_protection_keys");

                    b.ToTable("sb_data_protection_keys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("sb_pk_sb_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("sb_ix_sb_asp_net_role_claims_role_id");

                    b.ToTable("sb_asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("sb_pk_sb_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("sb_ix_sb_asp_net_user_claims_user_id");

                    b.ToTable("sb_asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("sb_pk_sb_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("sb_ix_sb_asp_net_user_logins_user_id");

                    b.ToTable("sb_asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId")
                        .HasName("sb_pk_sb_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("sb_ix_sb_asp_net_user_roles_role_id");

                    b.ToTable("sb_asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("sb_pk_sb_asp_net_user_tokens");

                    b.ToTable("sb_asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("SquareBuddy.Data.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id")
                        .HasName("sb_pk_sb_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("sb_role_name_index");

                    b.ToTable("sb_asp_net_roles", (string)null);
                });

            modelBuilder.Entity("SquareBuddy.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id")
                        .HasName("sb_pk_sb_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("sb_email_index");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("sb_user_name_index");

                    b.ToTable("sb_asp_net_users", (string)null);
                });

            modelBuilder.Entity("SquareBuddy.Data.Entities.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("sb_pk_sb_boards");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("sb_ix_sb_boards_subscription_id");

                    b.ToTable("sb_boards");
                });

            modelBuilder.Entity("SquareBuddy.Data.Entities.BoardConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgeGroup")
                        .HasColumnType("integer");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvaluatorUserPrompt")
                        .HasColumnType("text");

                    b.Property<string>("EvaluatorUserPromptCompiled")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProducerUserPrompt")
                        .HasColumnType("text");

                    b.Property<string>("ProducerUserPromptCompiled")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Voice")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("sb_pk_sb_board_configs");

                    b.HasIndex("BoardId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("sb_ix_sb_board_configs_board_id_created_at");

                    b.ToTable("sb_board_configs");
                });

            modelBuilder.Entity("SquareBuddy.Data.Entities.CreditTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("StripeEventId")
                        .HasColumnType("text");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("sb_pk_sb_credit_transactions");

                    b.HasIndex("StripeEventId")
                        .IsUnique()
                        .HasDatabaseName("sb_ix_sb_credit_transactions_stripe_event_id");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("sb_ix_sb_credit_transactions_subscription_id");

                    b.ToTable("sb_credit_transactions");
                });

            modelBuilder.Entity("SquareBuddy.Data.Entities.StoryRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedWith")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SceneGraph")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("sb_pk_sb_story_requests");

                    b.HasIndex("ConfigId")
                        .HasDatabaseName("sb_ix_sb_story_requests_config_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("sb_ix_sb_story_requests_status");

                    b.HasIndex("BoardId", "CreatedAt")
                        .HasDatabaseName("sb_ix_sb_story_requests_board_id_created_at");

                    b.ToTable("sb_story_requests");
                });

            modelBuilder.Entity("SquareBuddy.Data.Entities.StoryRequestChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioObjectKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("StoryRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("sb_pk_sb_story_request_chunks");

                    b.HasIndex("StoryRequestId")
                        .HasDatabaseName("sb_ix_sb_story_request_chunks_story_request_id");

                    b.HasIndex("StoryRequestId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("sb_ix_sb_story_request_chunks_story_request_id_sequence");

                    b.ToTable("sb_story_request_chunks");
                });

            modelBuilder.Entity("SquareBuddy.Data.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.Property<string>("StripePriceId")
                        .HasColumnType("text");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("text");

                    b.Property<int>("SubscriptionCreditBalance")
                        .HasColumnType("integer");

                    b.Property<int>("TopUpCreditBalance")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("sb_pk_sb_subscriptions");

                    b.ToTable("sb_subscriptions");
                });

            modelBuilder.Entity("SquareBuddy.Data.Entities.SubscriptionUser", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubscriptionId", "UserId")
                        .HasName("sb_pk_sb_subscription_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("sb_ix_sb_subscription_users_user_id");

                    b.ToTable("sb_subscription_users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("SquareBuddy.Data.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sb_fk_sb_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SquareBuddy.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sb_fk_sb_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SquareBuddy.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sb_fk_sb_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("SquareBuddy.Data.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sb_fk_sb_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("SquareBuddy.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sb_fk_sb_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SquareBuddy.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sb_fk_sb_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("SquareBuddy.Data.Entities.Board", b =>
                {
                    b.HasOne("SquareBuddy.Data.Entities.Subscription", "Subscription")
                        .WithMany("Boards")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sb_fk_sb_boards_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("SquareBuddy.Data.Entities.BoardConfig", b =>
                {
                    b.HasOne("SquareBuddy.Data.Entities.Board", "Board")
                        .WithMany("Configs")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sb_fk_sb_board_configs_sb_boards_board_id");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("SquareBuddy.Data.Entities.CreditTransaction", b =>
                {
                    b.HasOne("SquareBuddy.Data.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sb_fk_sb_credit_transactions_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("SquareBuddy.Data.Entities.StoryRequest", b =>
                {
                    b.HasOne("SquareBuddy.Data.Entities.Board", "Board")
                        .WithMany("Stories")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sb_fk_sb_story_requests_sb_boards_board_id");

                    b.HasOne("SquareBuddy.Data.Entities.BoardConfig", "Config")
                        .WithMany("Stories")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("sb_fk_sb_story_requests_sb_board_configs_config_id");

                    b.Navigation("Board");

                    b.Navigation("Config");
                });

            modelBuilder.Entity("SquareBuddy.Data.Entities.StoryRequestChunk", b =>
                {
                    b.HasOne("SquareBuddy.Data.Entities.StoryRequest", "StoryRequest")
                        .WithMany("Chunks")
                        .HasForeignKey("StoryRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sb_fk_sb_story_request_chunks_sb_story_requests_story_request_id");

                    b.Navigation("StoryRequest");
                });

            modelBuilder.Entity("SquareBuddy.Data.Entities.SubscriptionUser", b =>
                {
                    b.HasOne("SquareBuddy.Data.Entities.Subscription", "Subscription")
                        .WithMany("SubscriptionUsers")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sb_fk_sb_subscription_users_sb_subscriptions_subscription_id");

                    b.HasOne("SquareBuddy.Data.Entities.ApplicationUser", "User")
                        .WithMany("SubscriptionUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sb_fk_sb_subscription_users_sb_asp_net_users_user_id");

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SquareBuddy.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("SubscriptionUsers");
                });

            modelBuilder.Entity("SquareBuddy.Data.Entities.Board", b =>
                {
                    b.Navigation("Configs");

                    b.Navigation("Stories");
                });

            modelBuilder.Entity("SquareBuddy.Data.Entities.BoardConfig", b =>
                {
                    b.Navigation("Stories");
                });

            modelBuilder.Entity("SquareBuddy.Data.Entities.StoryRequest", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("SquareBuddy.Data.Entities.Subscription", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("SubscriptionUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
