# Framework config
Logging:
  LogLevel:
    Default: Warning

AllowedHosts: "*"

ConnectionStrings:
   buyalan: "..."


# Infra defaults
MINIO_ENDPOINT: http://localhost:9000
MINIO_BUCKET: buyalan
MINIO_ACCESS_KEY: minioadmin
MINIO_SECRET_KEY: minioadmin

LITELLM_ENDPOINT: http://localhost:8080
LITELLM_API_KEY: sk-1234

# Application config
