// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5000/' | (string & {});
};

export type AgentCatalogProductAccessStateResult = {
    agentId: string;
    subscriptionId: string;
    hasExplicitAssignments: boolean;
    subscriptionCatalogProductIds: Array<string>;
};

export type AgentCatalogProductItem = {
    subscriptionCatalogProductId: string;
    squareItemId: string;
    squareVariationId: string;
    itemName: string;
    variationName: string;
    description: null | string;
    sku: null | string;
    basePriceAmount: number;
    basePriceCurrency: null | string;
    isSellable: boolean;
    isDeleted: boolean;
    isAssigned: boolean;
};

export type AgentErrorResult = {
    errorCode: string;
    message: string;
};

export type AgentItem = {
    agentId: string;
    name: string;
    personality: null | AgentPersonality;
    isOperationalReady: boolean;
    createdAt: string;
    updatedAt: string;
};

export type AgentPersonality = 'Casual' | 'Balanced' | 'Business';

export type AgentResult = {
    agentId: string;
    subscriptionId: string;
    name: string;
    personality: null | AgentPersonality;
    personalityPromptRaw: null | string;
    twilioPhoneNumber: null | string;
    whatsappNumber: null | string;
    telegramBotToken: null | string;
    isOperationalReady: boolean;
    createdAt: string;
    updatedAt: string;
};

export type AgentSalesZipCodeStateResult = {
    agentId: string;
    subscriptionId: string;
    hasExplicitZipRestrictions: boolean;
    zipCodesNormalized: Array<string>;
};

export type AppInfo = {
    appName: string;
    appVersion: string;
};

export type ConfirmNewsletterSubscriptionInput = {
    token: null | string;
};

export type ConfirmNewsletterSubscriptionResult = {
    accepted: boolean;
};

export type ConversationListItem = {
    conversationId: string;
    participantExternalId: string;
    channel: MessageChannel;
    lastMessagePreview: null | string;
    lastMessageAt: null | string;
    lastMessageRole: null | MessageRole;
    unreadCount: number;
    hasUnread: boolean;
};

export type ConversationMessageItem = {
    messageId: string;
    role: MessageRole;
    content: string;
    from: string;
    to: string;
    occurredAt: string;
    isRead: boolean;
    readAt: null | string;
};

export type CreateNewsletterSubscriptionInput = {
    email: null | string;
};

export type CreateNewsletterSubscriptionResult = {
    accepted: boolean;
};

export type CreateSubscriptionOnboardingAgentResult = {
    agentId: string;
    state: GetSubscriptionOnboardingStateResult;
};

export type CurrentUserResult = {
    id: string;
    email: string;
    displayName: string;
    roles: Array<string>;
    activeSubscriptionId: null | string;
    isOnboarded: boolean;
};

export type DeleteAgentResult = {
    deleted: boolean;
};

export type DeleteSubscriptionInvitationResult = {
    revoked: boolean;
};

export type DeleteSubscriptionMemberResult = {
    deleted: boolean;
};

export type DeleteSubscriptionSquareConnectionResult = {
    disconnected: boolean;
};

export type ExternalLoginProviderItem = {
    name: string;
    displayName: string;
};

export type GetActiveSubscriptionResult = {
    subscriptionId: string;
};

export type GetAgentCatalogProductsResult = {
    hasExplicitAssignments?: boolean;
    items?: Array<AgentCatalogProductItem>;
    hasNextPage?: boolean;
    skip?: number;
    take?: number;
};

export type GetAgentConversationsResult = {
    items?: Array<ConversationListItem>;
    hasNextPage?: boolean;
    skip?: number;
    take?: number;
};

export type GetAgentsResult = {
    items?: Array<AgentItem>;
    hasNextPage?: boolean;
    skip?: number;
    take?: number;
};

export type GetConversationMessagesResult = {
    items?: Array<ConversationMessageItem>;
    hasNextPage?: boolean;
    skip?: number;
    take?: number;
};

export type GetExternalLoginProvidersResult = {
    providers: Array<ExternalLoginProviderItem>;
};

export type GetSubscriptionInvitationByTokenResult = {
    status: string;
    invitation: SubscriptionInvitationLookupItem;
};

export type GetSubscriptionInvitationLinkResult = {
    invitationUrl: string;
};

export type GetSubscriptionMembersResult = {
    subscriptionId: string;
    invitations: Array<SubscriptionInvitationItem>;
    members: Array<SubscriptionMemberItem>;
    availableRoles: Array<SubscriptionUserRole>;
};

export type GetSubscriptionOnboardingStateResult = {
    status: string;
    currentStep: string;
    steps: Array<OnboardingStepState>;
    primaryAgentId: null | string;
    canFinalize: boolean;
    profilePrefill: OnboardingProfilePrefill;
    channelsPrefill: OnboardingChannelsPrefill;
    invitations: OnboardingInvitationStepResult;
};

export type GetSubscriptionSquareCatalogProductsResult = {
    items?: Array<SubscriptionSquareCatalogProductItem>;
    total?: number;
    skip?: number;
    take?: number;
    sort?: null | Array<SortInfo>;
};

export type GetSubscriptionSquareCatalogSyncStateResult = {
    subscriptionId: string;
    status: string;
    lastTriggerSource: null | string;
    lastSyncedBeginTimeUtc: null | string;
    nextScheduledSyncAtUtc: null | string;
    lastSyncStartedAtUtc: null | string;
    lastSyncCompletedAtUtc: null | string;
    syncInProgress: boolean;
    pendingResync: boolean;
    lastErrorCode: null | string;
    lastErrorMessage: null | string;
    cachedProductCount: number;
    sellableProductCount: number;
    deletedProductCount: number;
};

export type IngestTelegramMessageInput = {
    message?: null | TelegramMessageInput;
};

export type IngestTwilioTextInput = {
    toCountry?: null | string;
    toState?: null | string;
    smsMessageSid?: null | string;
    numMedia?: null | string;
    toCity?: null | string;
    fromZip?: null | string;
    smsSid?: null | string;
    fromState?: null | string;
    smsStatus?: null | string;
    fromCity?: null | string;
    body?: string;
    fromCountry?: null | string;
    to?: string;
    toZip?: null | string;
    numSegments?: null | string;
    messageSid?: null | string;
    accountSid?: null | string;
    from?: string;
    apiVersion?: null | string;
};

export type MarkConversationMessageReadResult = {
    messageId: string;
    isRead: boolean;
    readAt: null | string;
    conversationUnreadCount: number;
};

export type MarkConversationReadResult = {
    conversationId: string;
    markedCount: number;
    conversationUnreadCount: number;
};

export type MessageChannel = 'WhatsApp' | 'Telegram' | 'SMS';

export type MessageRole = 'Customer' | 'Agent' | 'Operator';

export type OnboardingChannelsPrefill = {
    twilioPhoneNumber: null | string;
    whatsappNumber: null | string;
    hasTelegramBotToken: boolean;
};

export type OnboardingErrorResult = {
    errorCode: string;
    message: string;
};

export type OnboardingInvitationStepResult = {
    invitations: Array<SubscriptionInvitationItem>;
    members: Array<SubscriptionMemberItem>;
    suggestions: Array<SquareTeamMemberSuggestionItem>;
    availableRoles: Array<SubscriptionUserRole>;
};

export type OnboardingProfilePrefill = {
    name: null | string;
    personality: null | AgentPersonality;
};

export type OnboardingStepState = {
    step: string;
    status: string;
    isSkippable: boolean;
    dependsOn: Array<string>;
};

export type PatchOnboardingAgentChannelsInput = {
    twilioPhoneNumber: null | string;
    telegramBotToken: null | string;
    whatsappNumber: null | string;
};

export type PatchOnboardingAgentProfileInput = {
    name: null | string;
    personality: null | AgentPersonality;
};

export type PostAgentInput = {
    name: null | string;
    personality: null | AgentPersonality;
    personalityPromptRaw: null | string;
    twilioPhoneNumber: null | string;
    telegramBotToken: null | string;
    whatsappNumber: null | string;
};

export type PostSubscriptionInvitationAcceptResult = {
    status: string;
    subscriptionId: string;
    membershipCreated: boolean;
};

export type PostSubscriptionInvitationInput = {
    email: null | string;
    role: null | SubscriptionUserRole;
};

export type PostSubscriptionSquareCatalogSyncResult = {
    enqueued: boolean;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: number;
    detail?: null | string;
    instance?: null | string;
};

export type PutAgentCatalogProductsInput = {
    subscriptionCatalogProductIds: Array<string>;
};

export type PutAgentSalesZipCodesInput = {
    zipCodes: Array<string>;
};

export type PutSubscriptionMemberRoleInput = {
    role: null | SubscriptionUserRole;
};

export type SortInfo = {
    field: string;
    isAsc: boolean;
};

export type SquareConnectionErrorResult = {
    errorCode: string;
    message: string;
};

export type SquareTeamMemberSuggestionItem = {
    displayName: string;
    email: string;
};

export type StartSubscriptionSquareConnectAuthorizeResult = {
    authorizeUrl: string;
};

export type SubscriptionCatalogSyncErrorResult = {
    errorCode: string;
    message: string;
};

export type SubscriptionInvitationItem = {
    invitationId: string;
    email: string;
    role: SubscriptionUserRole;
    status: string;
    sentAtUtc: string;
    acceptedAtUtc: null | string;
    revokedAtUtc: null | string;
    expiresAtUtc: string;
    invitedByUserId: string;
    invitedByDisplayName: string;
    canResend: boolean;
    canCopyLink: boolean;
    canRevoke: boolean;
};

export type SubscriptionInvitationLookupItem = {
    invitationId: string;
    subscriptionId: string;
    maskedEmail: string;
    role: SubscriptionUserRole;
    sentAtUtc: string;
    subscriptionDisplayText: string;
};

export type SubscriptionMemberItem = {
    userId: string;
    email: string;
    displayName: string;
    role: SubscriptionUserRole;
    joinedAtUtc: string;
    isCurrentUser: boolean;
    canUpdateRole: boolean;
    canDelete: boolean;
};

export type SubscriptionMemberManagementErrorResult = {
    code: string;
    message: string;
};

export type SubscriptionSquareCatalogProductItem = {
    subscriptionCatalogProductId: string;
    squareItemId: string;
    squareVariationId: string;
    itemName: string;
    variationName: string;
    description: null | string;
    sku: null | string;
    basePriceAmount: number;
    basePriceCurrency: null | string;
    isSellable: boolean;
    isDeleted: boolean;
    squareUpdatedAtUtc: null | string;
    locationCount: number;
};

export type SubscriptionUserRole = number;

export type TelegramChatInput = {
    id?: number;
};

export type TelegramMessageInput = {
    text?: null | string;
    date?: number;
    from?: null | TelegramUserInput;
    chat?: null | TelegramChatInput;
};

export type TelegramUserInput = {
    id?: number;
};

export type GetAppInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetAppInfoResponses = {
    /**
     * OK
     */
    200: AppInfo;
};

export type GetAppInfoResponse = GetAppInfoResponses[keyof GetAppInfoResponses];

export type PostWebhooksTelegramByBotTokenData = {
    body: IngestTelegramMessageInput;
    path: {
        botToken: string;
    };
    query?: never;
    url: '/webhooks/telegram/{botToken}';
};

export type PostWebhooksTelegramByBotTokenErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostWebhooksTelegramByBotTokenError = PostWebhooksTelegramByBotTokenErrors[keyof PostWebhooksTelegramByBotTokenErrors];

export type PostWebhooksTelegramByBotTokenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostWebhooksSquareCatalogData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/webhooks/square/catalog';
};

export type PostWebhooksSquareCatalogErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type PostWebhooksSquareCatalogResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetSubscriptionsSquareCallbackData = {
    body?: never;
    path?: never;
    query?: {
        code?: string;
        state?: string;
        error?: string;
    };
    url: '/subscriptions/square/callback';
};

export type GetSubscriptionsSquareCallbackResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetSubscriptionInvitationsByTokenData = {
    body?: never;
    path: {
        token: string;
    };
    query?: never;
    url: '/subscription-invitations/{token}';
};

export type GetSubscriptionInvitationsByTokenErrors = {
    /**
     * Not Found
     */
    404: SubscriptionMemberManagementErrorResult;
};

export type GetSubscriptionInvitationsByTokenError = GetSubscriptionInvitationsByTokenErrors[keyof GetSubscriptionInvitationsByTokenErrors];

export type GetSubscriptionInvitationsByTokenResponses = {
    /**
     * OK
     */
    200: GetSubscriptionInvitationByTokenResult;
};

export type GetSubscriptionInvitationsByTokenResponse = GetSubscriptionInvitationsByTokenResponses[keyof GetSubscriptionInvitationsByTokenResponses];

export type PostSubscriptionInvitationsByTokenAcceptData = {
    body?: never;
    path: {
        token: string;
    };
    query?: never;
    url: '/subscription-invitations/{token}/accept';
};

export type PostSubscriptionInvitationsByTokenAcceptErrors = {
    /**
     * Bad Request
     */
    400: SubscriptionMemberManagementErrorResult;
    /**
     * Unauthorized
     */
    401: SubscriptionMemberManagementErrorResult;
    /**
     * Not Found
     */
    404: SubscriptionMemberManagementErrorResult;
};

export type PostSubscriptionInvitationsByTokenAcceptError = PostSubscriptionInvitationsByTokenAcceptErrors[keyof PostSubscriptionInvitationsByTokenAcceptErrors];

export type PostSubscriptionInvitationsByTokenAcceptResponses = {
    /**
     * OK
     */
    200: PostSubscriptionInvitationAcceptResult;
};

export type PostSubscriptionInvitationsByTokenAcceptResponse = PostSubscriptionInvitationsByTokenAcceptResponses[keyof PostSubscriptionInvitationsByTokenAcceptResponses];

export type IngestTextData = {
    body: IngestTwilioTextInput;
    path?: never;
    query?: never;
    url: '/webhooks/twilio/text';
};

export type IngestTextErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type IngestTextError = IngestTextErrors[keyof IngestTextErrors];

export type IngestTextResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAuthProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/providers';
};

export type GetAuthProvidersErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetAuthProvidersError = GetAuthProvidersErrors[keyof GetAuthProvidersErrors];

export type GetAuthProvidersResponses = {
    /**
     * OK
     */
    200: GetExternalLoginProvidersResult;
};

export type GetAuthProvidersResponse = GetAuthProvidersResponses[keyof GetAuthProvidersResponses];

export type GetAuthProvidersByProviderAuthorizeData = {
    body?: never;
    path: {
        provider: string;
    };
    query?: {
        returnUrl?: string;
    };
    url: '/auth/providers/{provider}/authorize';
};

export type GetAuthProvidersByProviderAuthorizeErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetAuthProvidersByProviderAuthorizeError = GetAuthProvidersByProviderAuthorizeErrors[keyof GetAuthProvidersByProviderAuthorizeErrors];

export type GetAuthExternalCallbackData = {
    body?: never;
    path?: never;
    query?: {
        returnUrl?: string;
        remoteError?: string;
    };
    url: '/auth/external-callback';
};

export type GetAuthExternalCallbackErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetAuthExternalCallbackError = GetAuthExternalCallbackErrors[keyof GetAuthExternalCallbackErrors];

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetAuthMeErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetAuthMeError = GetAuthMeErrors[keyof GetAuthMeErrors];

export type GetAuthMeResponses = {
    /**
     * OK
     */
    200: CurrentUserResult;
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAgentsData = {
    body?: never;
    path?: never;
    query: {
        subscription: string;
        skip?: number;
        take?: number;
    };
    url: '/agents';
};

export type GetAgentsErrors = {
    /**
     * Unauthorized
     */
    401: AgentErrorResult;
    /**
     * Forbidden
     */
    403: AgentErrorResult;
};

export type GetAgentsError = GetAgentsErrors[keyof GetAgentsErrors];

export type GetAgentsResponses = {
    /**
     * OK
     */
    200: GetAgentsResult;
};

export type GetAgentsResponse = GetAgentsResponses[keyof GetAgentsResponses];

export type PostAgentsData = {
    body?: never;
    path?: never;
    query: {
        subscription: string;
    };
    url: '/agents';
};

export type PostAgentsErrors = {
    /**
     * Unauthorized
     */
    401: AgentErrorResult;
    /**
     * Forbidden
     */
    403: AgentErrorResult;
};

export type PostAgentsError = PostAgentsErrors[keyof PostAgentsErrors];

export type PostAgentsResponses = {
    /**
     * OK
     */
    200: AgentResult;
};

export type PostAgentsResponse = PostAgentsResponses[keyof PostAgentsResponses];

export type DeleteAgentsByAgentIdData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}';
};

export type DeleteAgentsByAgentIdErrors = {
    /**
     * Unauthorized
     */
    401: AgentErrorResult;
    /**
     * Forbidden
     */
    403: AgentErrorResult;
    /**
     * Not Found
     */
    404: AgentErrorResult;
};

export type DeleteAgentsByAgentIdError = DeleteAgentsByAgentIdErrors[keyof DeleteAgentsByAgentIdErrors];

export type DeleteAgentsByAgentIdResponses = {
    /**
     * OK
     */
    200: DeleteAgentResult;
};

export type DeleteAgentsByAgentIdResponse = DeleteAgentsByAgentIdResponses[keyof DeleteAgentsByAgentIdResponses];

export type GetAgentsByAgentIdData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}';
};

export type GetAgentsByAgentIdErrors = {
    /**
     * Unauthorized
     */
    401: AgentErrorResult;
    /**
     * Forbidden
     */
    403: AgentErrorResult;
    /**
     * Not Found
     */
    404: AgentErrorResult;
};

export type GetAgentsByAgentIdError = GetAgentsByAgentIdErrors[keyof GetAgentsByAgentIdErrors];

export type GetAgentsByAgentIdResponses = {
    /**
     * OK
     */
    200: AgentResult;
};

export type GetAgentsByAgentIdResponse = GetAgentsByAgentIdResponses[keyof GetAgentsByAgentIdResponses];

export type PostAgentsByAgentIdData = {
    body: PostAgentInput;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}';
};

export type PostAgentsByAgentIdErrors = {
    /**
     * Bad Request
     */
    400: AgentErrorResult;
    /**
     * Unauthorized
     */
    401: AgentErrorResult;
    /**
     * Forbidden
     */
    403: AgentErrorResult;
    /**
     * Not Found
     */
    404: AgentErrorResult;
};

export type PostAgentsByAgentIdError = PostAgentsByAgentIdErrors[keyof PostAgentsByAgentIdErrors];

export type PostAgentsByAgentIdResponses = {
    /**
     * OK
     */
    200: AgentResult;
};

export type PostAgentsByAgentIdResponse = PostAgentsByAgentIdResponses[keyof PostAgentsByAgentIdResponses];

export type DeleteAgentsByAgentIdCatalogProductsData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/catalog/products';
};

export type DeleteAgentsByAgentIdCatalogProductsErrors = {
    /**
     * Unauthorized
     */
    401: AgentErrorResult;
    /**
     * Forbidden
     */
    403: AgentErrorResult;
    /**
     * Not Found
     */
    404: AgentErrorResult;
};

export type DeleteAgentsByAgentIdCatalogProductsError = DeleteAgentsByAgentIdCatalogProductsErrors[keyof DeleteAgentsByAgentIdCatalogProductsErrors];

export type DeleteAgentsByAgentIdCatalogProductsResponses = {
    /**
     * OK
     */
    200: AgentCatalogProductAccessStateResult;
};

export type DeleteAgentsByAgentIdCatalogProductsResponse = DeleteAgentsByAgentIdCatalogProductsResponses[keyof DeleteAgentsByAgentIdCatalogProductsResponses];

export type GetAgentsByAgentIdCatalogProductsData = {
    body?: never;
    path: {
        agentId: string;
    };
    query: {
        query?: string;
        skip: number;
        take: number;
    };
    url: '/agents/{agentId}/catalog/products';
};

export type GetAgentsByAgentIdCatalogProductsErrors = {
    /**
     * Unauthorized
     */
    401: AgentErrorResult;
    /**
     * Forbidden
     */
    403: AgentErrorResult;
    /**
     * Not Found
     */
    404: AgentErrorResult;
};

export type GetAgentsByAgentIdCatalogProductsError = GetAgentsByAgentIdCatalogProductsErrors[keyof GetAgentsByAgentIdCatalogProductsErrors];

export type GetAgentsByAgentIdCatalogProductsResponses = {
    /**
     * OK
     */
    200: GetAgentCatalogProductsResult;
};

export type GetAgentsByAgentIdCatalogProductsResponse = GetAgentsByAgentIdCatalogProductsResponses[keyof GetAgentsByAgentIdCatalogProductsResponses];

export type PutAgentsByAgentIdCatalogProductsData = {
    body: PutAgentCatalogProductsInput;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/catalog/products';
};

export type PutAgentsByAgentIdCatalogProductsErrors = {
    /**
     * Bad Request
     */
    400: AgentErrorResult;
    /**
     * Unauthorized
     */
    401: AgentErrorResult;
    /**
     * Forbidden
     */
    403: AgentErrorResult;
    /**
     * Not Found
     */
    404: AgentErrorResult;
};

export type PutAgentsByAgentIdCatalogProductsError = PutAgentsByAgentIdCatalogProductsErrors[keyof PutAgentsByAgentIdCatalogProductsErrors];

export type PutAgentsByAgentIdCatalogProductsResponses = {
    /**
     * OK
     */
    200: AgentCatalogProductAccessStateResult;
};

export type PutAgentsByAgentIdCatalogProductsResponse = PutAgentsByAgentIdCatalogProductsResponses[keyof PutAgentsByAgentIdCatalogProductsResponses];

export type DeleteAgentsByAgentIdSalesZipsData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/sales-zips';
};

export type DeleteAgentsByAgentIdSalesZipsErrors = {
    /**
     * Unauthorized
     */
    401: AgentErrorResult;
    /**
     * Forbidden
     */
    403: AgentErrorResult;
    /**
     * Not Found
     */
    404: AgentErrorResult;
};

export type DeleteAgentsByAgentIdSalesZipsError = DeleteAgentsByAgentIdSalesZipsErrors[keyof DeleteAgentsByAgentIdSalesZipsErrors];

export type DeleteAgentsByAgentIdSalesZipsResponses = {
    /**
     * OK
     */
    200: AgentSalesZipCodeStateResult;
};

export type DeleteAgentsByAgentIdSalesZipsResponse = DeleteAgentsByAgentIdSalesZipsResponses[keyof DeleteAgentsByAgentIdSalesZipsResponses];

export type GetAgentsByAgentIdSalesZipsData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/sales-zips';
};

export type GetAgentsByAgentIdSalesZipsErrors = {
    /**
     * Unauthorized
     */
    401: AgentErrorResult;
    /**
     * Forbidden
     */
    403: AgentErrorResult;
    /**
     * Not Found
     */
    404: AgentErrorResult;
};

export type GetAgentsByAgentIdSalesZipsError = GetAgentsByAgentIdSalesZipsErrors[keyof GetAgentsByAgentIdSalesZipsErrors];

export type GetAgentsByAgentIdSalesZipsResponses = {
    /**
     * OK
     */
    200: AgentSalesZipCodeStateResult;
};

export type GetAgentsByAgentIdSalesZipsResponse = GetAgentsByAgentIdSalesZipsResponses[keyof GetAgentsByAgentIdSalesZipsResponses];

export type PutAgentsByAgentIdSalesZipsData = {
    body: PutAgentSalesZipCodesInput;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/sales-zips';
};

export type PutAgentsByAgentIdSalesZipsErrors = {
    /**
     * Bad Request
     */
    400: AgentErrorResult;
    /**
     * Unauthorized
     */
    401: AgentErrorResult;
    /**
     * Forbidden
     */
    403: AgentErrorResult;
    /**
     * Not Found
     */
    404: AgentErrorResult;
};

export type PutAgentsByAgentIdSalesZipsError = PutAgentsByAgentIdSalesZipsErrors[keyof PutAgentsByAgentIdSalesZipsErrors];

export type PutAgentsByAgentIdSalesZipsResponses = {
    /**
     * OK
     */
    200: AgentSalesZipCodeStateResult;
};

export type PutAgentsByAgentIdSalesZipsResponse = PutAgentsByAgentIdSalesZipsResponses[keyof PutAgentsByAgentIdSalesZipsResponses];

export type GetAgentsByAgentIdConversationsData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/agents/{agentId}/conversations';
};

export type GetAgentsByAgentIdConversationsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetAgentsByAgentIdConversationsError = GetAgentsByAgentIdConversationsErrors[keyof GetAgentsByAgentIdConversationsErrors];

export type GetAgentsByAgentIdConversationsResponses = {
    /**
     * OK
     */
    200: GetAgentConversationsResult;
};

export type GetAgentsByAgentIdConversationsResponse = GetAgentsByAgentIdConversationsResponses[keyof GetAgentsByAgentIdConversationsResponses];

export type GetAgentsByAgentIdConversationsByConversationIdMessagesData = {
    body?: never;
    path: {
        agentId: string;
        conversationId: string;
    };
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/agents/{agentId}/conversations/{conversationId}/messages';
};

export type GetAgentsByAgentIdConversationsByConversationIdMessagesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetAgentsByAgentIdConversationsByConversationIdMessagesError = GetAgentsByAgentIdConversationsByConversationIdMessagesErrors[keyof GetAgentsByAgentIdConversationsByConversationIdMessagesErrors];

export type GetAgentsByAgentIdConversationsByConversationIdMessagesResponses = {
    /**
     * OK
     */
    200: GetConversationMessagesResult;
};

export type GetAgentsByAgentIdConversationsByConversationIdMessagesResponse = GetAgentsByAgentIdConversationsByConversationIdMessagesResponses[keyof GetAgentsByAgentIdConversationsByConversationIdMessagesResponses];

export type PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadData = {
    body?: never;
    path: {
        agentId: string;
        conversationId: string;
        messageId: string;
    };
    query?: never;
    url: '/agents/{agentId}/conversations/{conversationId}/messages/{messageId}/read';
};

export type PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadError = PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadErrors[keyof PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadErrors];

export type PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadResponses = {
    /**
     * OK
     */
    200: MarkConversationMessageReadResult;
};

export type PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadResponse = PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadResponses[keyof PatchAgentsByAgentIdConversationsByConversationIdMessagesByMessageIdReadResponses];

export type PatchAgentsByAgentIdConversationsByConversationIdReadData = {
    body?: never;
    path: {
        agentId: string;
        conversationId: string;
    };
    query?: never;
    url: '/agents/{agentId}/conversations/{conversationId}/read';
};

export type PatchAgentsByAgentIdConversationsByConversationIdReadErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PatchAgentsByAgentIdConversationsByConversationIdReadError = PatchAgentsByAgentIdConversationsByConversationIdReadErrors[keyof PatchAgentsByAgentIdConversationsByConversationIdReadErrors];

export type PatchAgentsByAgentIdConversationsByConversationIdReadResponses = {
    /**
     * OK
     */
    200: MarkConversationReadResult;
};

export type PatchAgentsByAgentIdConversationsByConversationIdReadResponse = PatchAgentsByAgentIdConversationsByConversationIdReadResponses[keyof PatchAgentsByAgentIdConversationsByConversationIdReadResponses];

export type PostSubscriptionsBySubscriptionIdSquareAuthorizeData = {
    body?: never;
    path: {
        subscriptionId: string;
    };
    query?: {
        returnUrl?: string;
    };
    url: '/subscriptions/{subscriptionId}/square/authorize';
};

export type PostSubscriptionsBySubscriptionIdSquareAuthorizeErrors = {
    /**
     * Bad Request
     */
    400: SquareConnectionErrorResult;
    /**
     * Unauthorized
     */
    401: SquareConnectionErrorResult;
    /**
     * Forbidden
     */
    403: SquareConnectionErrorResult;
};

export type PostSubscriptionsBySubscriptionIdSquareAuthorizeError = PostSubscriptionsBySubscriptionIdSquareAuthorizeErrors[keyof PostSubscriptionsBySubscriptionIdSquareAuthorizeErrors];

export type PostSubscriptionsBySubscriptionIdSquareAuthorizeResponses = {
    /**
     * OK
     */
    200: StartSubscriptionSquareConnectAuthorizeResult;
};

export type PostSubscriptionsBySubscriptionIdSquareAuthorizeResponse = PostSubscriptionsBySubscriptionIdSquareAuthorizeResponses[keyof PostSubscriptionsBySubscriptionIdSquareAuthorizeResponses];

export type PostSubscriptionsBySubscriptionIdSquareCatalogSyncData = {
    body?: never;
    path: {
        subscriptionId: string;
    };
    query?: never;
    url: '/subscriptions/{subscriptionId}/square/catalog/sync';
};

export type PostSubscriptionsBySubscriptionIdSquareCatalogSyncErrors = {
    /**
     * Unauthorized
     */
    401: SubscriptionCatalogSyncErrorResult;
    /**
     * Forbidden
     */
    403: SubscriptionCatalogSyncErrorResult;
};

export type PostSubscriptionsBySubscriptionIdSquareCatalogSyncError = PostSubscriptionsBySubscriptionIdSquareCatalogSyncErrors[keyof PostSubscriptionsBySubscriptionIdSquareCatalogSyncErrors];

export type PostSubscriptionsBySubscriptionIdSquareCatalogSyncResponses = {
    /**
     * OK
     */
    200: PostSubscriptionSquareCatalogSyncResult;
};

export type PostSubscriptionsBySubscriptionIdSquareCatalogSyncResponse = PostSubscriptionsBySubscriptionIdSquareCatalogSyncResponses[keyof PostSubscriptionsBySubscriptionIdSquareCatalogSyncResponses];

export type GetSubscriptionsBySubscriptionIdSquareCatalogSyncStateData = {
    body?: never;
    path: {
        subscriptionId: string;
    };
    query?: never;
    url: '/subscriptions/{subscriptionId}/square/catalog/sync-state';
};

export type GetSubscriptionsBySubscriptionIdSquareCatalogSyncStateErrors = {
    /**
     * Unauthorized
     */
    401: SubscriptionCatalogSyncErrorResult;
    /**
     * Forbidden
     */
    403: SubscriptionCatalogSyncErrorResult;
};

export type GetSubscriptionsBySubscriptionIdSquareCatalogSyncStateError = GetSubscriptionsBySubscriptionIdSquareCatalogSyncStateErrors[keyof GetSubscriptionsBySubscriptionIdSquareCatalogSyncStateErrors];

export type GetSubscriptionsBySubscriptionIdSquareCatalogSyncStateResponses = {
    /**
     * OK
     */
    200: GetSubscriptionSquareCatalogSyncStateResult;
};

export type GetSubscriptionsBySubscriptionIdSquareCatalogSyncStateResponse = GetSubscriptionsBySubscriptionIdSquareCatalogSyncStateResponses[keyof GetSubscriptionsBySubscriptionIdSquareCatalogSyncStateResponses];

export type GetSubscriptionsBySubscriptionIdSquareCatalogProductsData = {
    body?: never;
    path: {
        subscriptionId: string;
    };
    query: {
        query?: string;
        skip: number;
        take: number;
    };
    url: '/subscriptions/{subscriptionId}/square/catalog/products';
};

export type GetSubscriptionsBySubscriptionIdSquareCatalogProductsErrors = {
    /**
     * Unauthorized
     */
    401: SubscriptionCatalogSyncErrorResult;
    /**
     * Forbidden
     */
    403: SubscriptionCatalogSyncErrorResult;
};

export type GetSubscriptionsBySubscriptionIdSquareCatalogProductsError = GetSubscriptionsBySubscriptionIdSquareCatalogProductsErrors[keyof GetSubscriptionsBySubscriptionIdSquareCatalogProductsErrors];

export type GetSubscriptionsBySubscriptionIdSquareCatalogProductsResponses = {
    /**
     * OK
     */
    200: GetSubscriptionSquareCatalogProductsResult;
};

export type GetSubscriptionsBySubscriptionIdSquareCatalogProductsResponse = GetSubscriptionsBySubscriptionIdSquareCatalogProductsResponses[keyof GetSubscriptionsBySubscriptionIdSquareCatalogProductsResponses];

export type DeleteSubscriptionsBySubscriptionIdSquareConnectionData = {
    body?: never;
    path: {
        subscriptionId: string;
    };
    query?: never;
    url: '/subscriptions/{subscriptionId}/square/connection';
};

export type DeleteSubscriptionsBySubscriptionIdSquareConnectionErrors = {
    /**
     * Bad Request
     */
    400: SquareConnectionErrorResult;
    /**
     * Unauthorized
     */
    401: SquareConnectionErrorResult;
    /**
     * Forbidden
     */
    403: SquareConnectionErrorResult;
    /**
     * Not Found
     */
    404: SquareConnectionErrorResult;
};

export type DeleteSubscriptionsBySubscriptionIdSquareConnectionError = DeleteSubscriptionsBySubscriptionIdSquareConnectionErrors[keyof DeleteSubscriptionsBySubscriptionIdSquareConnectionErrors];

export type DeleteSubscriptionsBySubscriptionIdSquareConnectionResponses = {
    /**
     * OK
     */
    200: DeleteSubscriptionSquareConnectionResult;
};

export type DeleteSubscriptionsBySubscriptionIdSquareConnectionResponse = DeleteSubscriptionsBySubscriptionIdSquareConnectionResponses[keyof DeleteSubscriptionsBySubscriptionIdSquareConnectionResponses];

export type GetSubscriptionsBySubscriptionIdMembersData = {
    body?: never;
    path: {
        subscriptionId: string;
    };
    query?: never;
    url: '/subscriptions/{subscriptionId}/members';
};

export type GetSubscriptionsBySubscriptionIdMembersErrors = {
    /**
     * Unauthorized
     */
    401: SubscriptionMemberManagementErrorResult;
    /**
     * Forbidden
     */
    403: SubscriptionMemberManagementErrorResult;
};

export type GetSubscriptionsBySubscriptionIdMembersError = GetSubscriptionsBySubscriptionIdMembersErrors[keyof GetSubscriptionsBySubscriptionIdMembersErrors];

export type GetSubscriptionsBySubscriptionIdMembersResponses = {
    /**
     * OK
     */
    200: GetSubscriptionMembersResult;
};

export type GetSubscriptionsBySubscriptionIdMembersResponse = GetSubscriptionsBySubscriptionIdMembersResponses[keyof GetSubscriptionsBySubscriptionIdMembersResponses];

export type PostSubscriptionsBySubscriptionIdMembersInvitationsData = {
    body: PostSubscriptionInvitationInput;
    path: {
        subscriptionId: string;
    };
    query?: never;
    url: '/subscriptions/{subscriptionId}/members/invitations';
};

export type PostSubscriptionsBySubscriptionIdMembersInvitationsErrors = {
    /**
     * Bad Request
     */
    400: SubscriptionMemberManagementErrorResult;
    /**
     * Unauthorized
     */
    401: SubscriptionMemberManagementErrorResult;
    /**
     * Forbidden
     */
    403: SubscriptionMemberManagementErrorResult;
};

export type PostSubscriptionsBySubscriptionIdMembersInvitationsError = PostSubscriptionsBySubscriptionIdMembersInvitationsErrors[keyof PostSubscriptionsBySubscriptionIdMembersInvitationsErrors];

export type PostSubscriptionsBySubscriptionIdMembersInvitationsResponses = {
    /**
     * OK
     */
    200: SubscriptionInvitationItem;
};

export type PostSubscriptionsBySubscriptionIdMembersInvitationsResponse = PostSubscriptionsBySubscriptionIdMembersInvitationsResponses[keyof PostSubscriptionsBySubscriptionIdMembersInvitationsResponses];

export type PostSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdResendData = {
    body?: never;
    path: {
        subscriptionId: string;
        invitationId: string;
    };
    query?: never;
    url: '/subscriptions/{subscriptionId}/members/invitations/{invitationId}/resend';
};

export type PostSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdResendErrors = {
    /**
     * Bad Request
     */
    400: SubscriptionMemberManagementErrorResult;
    /**
     * Unauthorized
     */
    401: SubscriptionMemberManagementErrorResult;
    /**
     * Forbidden
     */
    403: SubscriptionMemberManagementErrorResult;
    /**
     * Not Found
     */
    404: SubscriptionMemberManagementErrorResult;
};

export type PostSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdResendError = PostSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdResendErrors[keyof PostSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdResendErrors];

export type PostSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdResendResponses = {
    /**
     * OK
     */
    200: SubscriptionInvitationItem;
};

export type PostSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdResendResponse = PostSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdResendResponses[keyof PostSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdResendResponses];

export type GetSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdLinkData = {
    body?: never;
    path: {
        subscriptionId: string;
        invitationId: string;
    };
    query?: never;
    url: '/subscriptions/{subscriptionId}/members/invitations/{invitationId}/link';
};

export type GetSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdLinkErrors = {
    /**
     * Bad Request
     */
    400: SubscriptionMemberManagementErrorResult;
    /**
     * Unauthorized
     */
    401: SubscriptionMemberManagementErrorResult;
    /**
     * Forbidden
     */
    403: SubscriptionMemberManagementErrorResult;
    /**
     * Not Found
     */
    404: SubscriptionMemberManagementErrorResult;
};

export type GetSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdLinkError = GetSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdLinkErrors[keyof GetSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdLinkErrors];

export type GetSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdLinkResponses = {
    /**
     * OK
     */
    200: GetSubscriptionInvitationLinkResult;
};

export type GetSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdLinkResponse = GetSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdLinkResponses[keyof GetSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdLinkResponses];

export type DeleteSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdData = {
    body?: never;
    path: {
        subscriptionId: string;
        invitationId: string;
    };
    query?: never;
    url: '/subscriptions/{subscriptionId}/members/invitations/{invitationId}';
};

export type DeleteSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdErrors = {
    /**
     * Bad Request
     */
    400: SubscriptionMemberManagementErrorResult;
    /**
     * Unauthorized
     */
    401: SubscriptionMemberManagementErrorResult;
    /**
     * Forbidden
     */
    403: SubscriptionMemberManagementErrorResult;
    /**
     * Not Found
     */
    404: SubscriptionMemberManagementErrorResult;
};

export type DeleteSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdError = DeleteSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdErrors[keyof DeleteSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdErrors];

export type DeleteSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdResponses = {
    /**
     * OK
     */
    200: DeleteSubscriptionInvitationResult;
};

export type DeleteSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdResponse = DeleteSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdResponses[keyof DeleteSubscriptionsBySubscriptionIdMembersInvitationsByInvitationIdResponses];

export type PutSubscriptionsBySubscriptionIdMembersByMemberUserIdRoleData = {
    body: PutSubscriptionMemberRoleInput;
    path: {
        subscriptionId: string;
        memberUserId: string;
    };
    query?: never;
    url: '/subscriptions/{subscriptionId}/members/{memberUserId}/role';
};

export type PutSubscriptionsBySubscriptionIdMembersByMemberUserIdRoleErrors = {
    /**
     * Bad Request
     */
    400: SubscriptionMemberManagementErrorResult;
    /**
     * Unauthorized
     */
    401: SubscriptionMemberManagementErrorResult;
    /**
     * Forbidden
     */
    403: SubscriptionMemberManagementErrorResult;
    /**
     * Not Found
     */
    404: SubscriptionMemberManagementErrorResult;
};

export type PutSubscriptionsBySubscriptionIdMembersByMemberUserIdRoleError = PutSubscriptionsBySubscriptionIdMembersByMemberUserIdRoleErrors[keyof PutSubscriptionsBySubscriptionIdMembersByMemberUserIdRoleErrors];

export type PutSubscriptionsBySubscriptionIdMembersByMemberUserIdRoleResponses = {
    /**
     * OK
     */
    200: SubscriptionMemberItem;
};

export type PutSubscriptionsBySubscriptionIdMembersByMemberUserIdRoleResponse = PutSubscriptionsBySubscriptionIdMembersByMemberUserIdRoleResponses[keyof PutSubscriptionsBySubscriptionIdMembersByMemberUserIdRoleResponses];

export type DeleteSubscriptionsBySubscriptionIdMembersByMemberUserIdData = {
    body?: never;
    path: {
        subscriptionId: string;
        memberUserId: string;
    };
    query?: never;
    url: '/subscriptions/{subscriptionId}/members/{memberUserId}';
};

export type DeleteSubscriptionsBySubscriptionIdMembersByMemberUserIdErrors = {
    /**
     * Bad Request
     */
    400: SubscriptionMemberManagementErrorResult;
    /**
     * Unauthorized
     */
    401: SubscriptionMemberManagementErrorResult;
    /**
     * Forbidden
     */
    403: SubscriptionMemberManagementErrorResult;
    /**
     * Not Found
     */
    404: SubscriptionMemberManagementErrorResult;
};

export type DeleteSubscriptionsBySubscriptionIdMembersByMemberUserIdError = DeleteSubscriptionsBySubscriptionIdMembersByMemberUserIdErrors[keyof DeleteSubscriptionsBySubscriptionIdMembersByMemberUserIdErrors];

export type DeleteSubscriptionsBySubscriptionIdMembersByMemberUserIdResponses = {
    /**
     * OK
     */
    200: DeleteSubscriptionMemberResult;
};

export type DeleteSubscriptionsBySubscriptionIdMembersByMemberUserIdResponse = DeleteSubscriptionsBySubscriptionIdMembersByMemberUserIdResponses[keyof DeleteSubscriptionsBySubscriptionIdMembersByMemberUserIdResponses];

export type GetOnboardingSubscriptionsActiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/onboarding/subscriptions/active';
};

export type GetOnboardingSubscriptionsActiveErrors = {
    /**
     * Unauthorized
     */
    401: OnboardingErrorResult;
    /**
     * Not Found
     */
    404: OnboardingErrorResult;
};

export type GetOnboardingSubscriptionsActiveError = GetOnboardingSubscriptionsActiveErrors[keyof GetOnboardingSubscriptionsActiveErrors];

export type GetOnboardingSubscriptionsActiveResponses = {
    /**
     * OK
     */
    200: GetActiveSubscriptionResult;
};

export type GetOnboardingSubscriptionsActiveResponse = GetOnboardingSubscriptionsActiveResponses[keyof GetOnboardingSubscriptionsActiveResponses];

export type GetOnboardingSubscriptionsBySubscriptionIdStateData = {
    body?: never;
    path: {
        subscriptionId: string;
    };
    query: {
        resumeMode: boolean;
    };
    url: '/onboarding/subscriptions/{subscriptionId}/state';
};

export type GetOnboardingSubscriptionsBySubscriptionIdStateErrors = {
    /**
     * Unauthorized
     */
    401: OnboardingErrorResult;
    /**
     * Forbidden
     */
    403: OnboardingErrorResult;
    /**
     * Not Found
     */
    404: OnboardingErrorResult;
};

export type GetOnboardingSubscriptionsBySubscriptionIdStateError = GetOnboardingSubscriptionsBySubscriptionIdStateErrors[keyof GetOnboardingSubscriptionsBySubscriptionIdStateErrors];

export type GetOnboardingSubscriptionsBySubscriptionIdStateResponses = {
    /**
     * OK
     */
    200: GetSubscriptionOnboardingStateResult;
};

export type GetOnboardingSubscriptionsBySubscriptionIdStateResponse = GetOnboardingSubscriptionsBySubscriptionIdStateResponses[keyof GetOnboardingSubscriptionsBySubscriptionIdStateResponses];

export type PostOnboardingSubscriptionsBySubscriptionIdAgentsData = {
    body?: never;
    path: {
        subscriptionId: string;
    };
    query?: never;
    url: '/onboarding/subscriptions/{subscriptionId}/agents';
};

export type PostOnboardingSubscriptionsBySubscriptionIdAgentsErrors = {
    /**
     * Unauthorized
     */
    401: OnboardingErrorResult;
    /**
     * Forbidden
     */
    403: OnboardingErrorResult;
    /**
     * Not Found
     */
    404: OnboardingErrorResult;
};

export type PostOnboardingSubscriptionsBySubscriptionIdAgentsError = PostOnboardingSubscriptionsBySubscriptionIdAgentsErrors[keyof PostOnboardingSubscriptionsBySubscriptionIdAgentsErrors];

export type PostOnboardingSubscriptionsBySubscriptionIdAgentsResponses = {
    /**
     * OK
     */
    200: CreateSubscriptionOnboardingAgentResult;
};

export type PostOnboardingSubscriptionsBySubscriptionIdAgentsResponse = PostOnboardingSubscriptionsBySubscriptionIdAgentsResponses[keyof PostOnboardingSubscriptionsBySubscriptionIdAgentsResponses];

export type PatchOnboardingAgentsByAgentIdProfileData = {
    body: PatchOnboardingAgentProfileInput;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/onboarding/agents/{agentId}/profile';
};

export type PatchOnboardingAgentsByAgentIdProfileErrors = {
    /**
     * Bad Request
     */
    400: OnboardingErrorResult;
    /**
     * Unauthorized
     */
    401: OnboardingErrorResult;
    /**
     * Forbidden
     */
    403: OnboardingErrorResult;
    /**
     * Not Found
     */
    404: OnboardingErrorResult;
};

export type PatchOnboardingAgentsByAgentIdProfileError = PatchOnboardingAgentsByAgentIdProfileErrors[keyof PatchOnboardingAgentsByAgentIdProfileErrors];

export type PatchOnboardingAgentsByAgentIdProfileResponses = {
    /**
     * OK
     */
    200: GetSubscriptionOnboardingStateResult;
};

export type PatchOnboardingAgentsByAgentIdProfileResponse = PatchOnboardingAgentsByAgentIdProfileResponses[keyof PatchOnboardingAgentsByAgentIdProfileResponses];

export type PatchOnboardingAgentsByAgentIdChannelsData = {
    body: PatchOnboardingAgentChannelsInput;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/onboarding/agents/{agentId}/channels';
};

export type PatchOnboardingAgentsByAgentIdChannelsErrors = {
    /**
     * Bad Request
     */
    400: OnboardingErrorResult;
    /**
     * Unauthorized
     */
    401: OnboardingErrorResult;
    /**
     * Forbidden
     */
    403: OnboardingErrorResult;
    /**
     * Not Found
     */
    404: OnboardingErrorResult;
};

export type PatchOnboardingAgentsByAgentIdChannelsError = PatchOnboardingAgentsByAgentIdChannelsErrors[keyof PatchOnboardingAgentsByAgentIdChannelsErrors];

export type PatchOnboardingAgentsByAgentIdChannelsResponses = {
    /**
     * OK
     */
    200: GetSubscriptionOnboardingStateResult;
};

export type PatchOnboardingAgentsByAgentIdChannelsResponse = PatchOnboardingAgentsByAgentIdChannelsResponses[keyof PatchOnboardingAgentsByAgentIdChannelsResponses];

export type PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsData = {
    body: PostSubscriptionInvitationInput;
    path: {
        subscriptionId: string;
    };
    query?: never;
    url: '/onboarding/subscriptions/{subscriptionId}/members/invitations';
};

export type PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsErrors = {
    /**
     * Bad Request
     */
    400: OnboardingErrorResult;
    /**
     * Unauthorized
     */
    401: OnboardingErrorResult;
    /**
     * Forbidden
     */
    403: OnboardingErrorResult;
    /**
     * Not Found
     */
    404: OnboardingErrorResult;
};

export type PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsError = PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsErrors[keyof PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsErrors];

export type PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsResponses = {
    /**
     * OK
     */
    200: GetSubscriptionOnboardingStateResult;
};

export type PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsResponse = PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsResponses[keyof PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsResponses];

export type PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsCompleteData = {
    body?: never;
    path: {
        subscriptionId: string;
    };
    query?: never;
    url: '/onboarding/subscriptions/{subscriptionId}/members/invitations/complete';
};

export type PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsCompleteErrors = {
    /**
     * Bad Request
     */
    400: OnboardingErrorResult;
    /**
     * Unauthorized
     */
    401: OnboardingErrorResult;
    /**
     * Forbidden
     */
    403: OnboardingErrorResult;
    /**
     * Not Found
     */
    404: OnboardingErrorResult;
};

export type PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsCompleteError = PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsCompleteErrors[keyof PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsCompleteErrors];

export type PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsCompleteResponses = {
    /**
     * OK
     */
    200: GetSubscriptionOnboardingStateResult;
};

export type PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsCompleteResponse = PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsCompleteResponses[keyof PostOnboardingSubscriptionsBySubscriptionIdMembersInvitationsCompleteResponses];

export type PostOnboardingSubscriptionsBySubscriptionIdFinalizeData = {
    body?: never;
    path: {
        subscriptionId: string;
    };
    query?: never;
    url: '/onboarding/subscriptions/{subscriptionId}/finalize';
};

export type PostOnboardingSubscriptionsBySubscriptionIdFinalizeErrors = {
    /**
     * Bad Request
     */
    400: OnboardingErrorResult;
    /**
     * Unauthorized
     */
    401: OnboardingErrorResult;
    /**
     * Forbidden
     */
    403: OnboardingErrorResult;
    /**
     * Not Found
     */
    404: OnboardingErrorResult;
};

export type PostOnboardingSubscriptionsBySubscriptionIdFinalizeError = PostOnboardingSubscriptionsBySubscriptionIdFinalizeErrors[keyof PostOnboardingSubscriptionsBySubscriptionIdFinalizeErrors];

export type PostOnboardingSubscriptionsBySubscriptionIdFinalizeResponses = {
    /**
     * OK
     */
    200: GetSubscriptionOnboardingStateResult;
};

export type PostOnboardingSubscriptionsBySubscriptionIdFinalizeResponse = PostOnboardingSubscriptionsBySubscriptionIdFinalizeResponses[keyof PostOnboardingSubscriptionsBySubscriptionIdFinalizeResponses];

export type PostNewsletterSubscribeData = {
    body: CreateNewsletterSubscriptionInput;
    path?: never;
    query?: never;
    url: '/newsletter/subscribe';
};

export type PostNewsletterSubscribeErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostNewsletterSubscribeError = PostNewsletterSubscribeErrors[keyof PostNewsletterSubscribeErrors];

export type PostNewsletterSubscribeResponses = {
    /**
     * OK
     */
    200: CreateNewsletterSubscriptionResult;
};

export type PostNewsletterSubscribeResponse = PostNewsletterSubscribeResponses[keyof PostNewsletterSubscribeResponses];

export type PostNewsletterConfirmData = {
    body: ConfirmNewsletterSubscriptionInput;
    path?: never;
    query?: never;
    url: '/newsletter/confirm';
};

export type PostNewsletterConfirmResponses = {
    /**
     * OK
     */
    200: ConfirmNewsletterSubscriptionResult;
};

export type PostNewsletterConfirmResponse = PostNewsletterConfirmResponses[keyof PostNewsletterConfirmResponses];
