# Framework config
Logging:
  LogLevel:
    Default: Debug
    Microsoft.AspNetCore: Debug
    Microsoft.AspNetCore.Authentication: Debug
    Microsoft.AspNetCore.Identity: Debug

AllowedHosts: "*"

ConnectionStrings:
   squarebuddydb: "..."


# Infra defaults
MINIO_ENDPOINT: http://localhost:9000
MINIO_BUCKET: squarebuddy
MINIO_ACCESS_KEY: minioadmin
MINIO_SECRET_KEY: minioadmin

# Application config
